### ISSUE TITLE
Custom bootstrap scripts/snippets?

### ISSUE THREAD

**Issue by ChillarAnand** [django-extensions/django-extensions#1009]
I have set of utility functions on a per project basis. I am wondering if shell plus can provide an option to load them automatically on startup?

**Comment by trbs** [comment]
`shell_plus` can load user specified import at startup. See documentation on this at: http://django-extensions.readthedocs.io/en/latest/shell_plus.html#additional-imports

Hope this helps.

**Comment by ChillarAnand** [comment]
That won't work with if it has django speicic statments? Eg:

    user = User.objects.first()

For this to work, again django needs to be configured at the beginning.

To avoid that, right now I am loading everytime shell_plus is started

    In [1]: exec(open("./scripts/ipython_init.py").read())

Is there a way to automate this?

**Comment by trbs** [comment]
```django.setup()``` is ran before the imports isn't that enough ?

If it's not, please create a test case / reproducible gist or git repo. Not sure when I would be able to work on it but maybe I or somebody else could create a PR based on that.

**Comment by ChillarAnand** [comment]
Create a file foo.py with 

    user = User.objects.first()

Add this file to shell_plus imports

    SHELL_PLUS_PRE_IMPORTS = (
        ('foo', '*'),
    )

It fails with 
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django_extensions/management/commands/shell_plus.py", line 418, in handle
    shell()
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django_extensions/management/commands/shell_plus.py", line 280, in run_ipython
    imported_objects = import_objects(options, self.style)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django_extensions/management/shells.py", line 117, in import_objects
    imports = import_items(SHELL_PLUS_PRE_IMPORTS, style, quiet_load=quiet_load)
  File "/home/chillaranand/.virtualenvs/mycroft/lib/python3.5/site-packages/django_extensions/management/shells.py", line 56, in import_items
    imported_object = __import__(directive[0], {}, {}, directive[1])
  File "/home/chillaranand/projects/appknox/mycroft/scripts/ipython_init.py", line 1, in <module>
    user = User.objects.first()
NameError: name 'User' is not defined
```

**Comment by trbs** [comment]
Ah i see, yes you do need to import everything you need inside that `foo.py` script.

I would not want to change that behavior. Since that would mean no `foo.py` magically has items in it's scope that seemingly come out of nowhere.

If you really want, and I would highly discourage it, you could always `from django_extensions.management.shell import import_objects` put that in `foo.py` and inject the result into the global scope. (again please don't but if you must you could :) )
