### ISSUE TITLE
ImportError: No module named 'config'

### ISSUE THREAD

**Issue by Narsail** [django-extensions/django-extensions#1014]
I use the IPython kernels together with the jupyter notebook via the shell_plus command in a docker environment. I can open the notebook via the provided link but can't get any kernel to work. Neither in the root directory nor a subdirectory is it possible to run a notebook with a working kernel.

Any ideas what i do wrong? Do you need more information about the system?

Traceback:
```
jupyter_1   | [I 21:11:49.348 NotebookApp] Kernel started: 28e0cc8d-f2a3-485d-94f1-168e42c97529
jupyter_1   | [IPKernelApp] WARNING | Error in loading extension: django_extensions.management.notebook_extension
jupyter_1   | Check your config files in /root/.ipython/profile_default
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
jupyter_1   |     self.shell.extension_manager.load_extension(ext)
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/IPython/core/extensions.py", line 85, in load_extension
jupyter_1   |     if self._call_load_ipython_extension(mod):
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_extension
jupyter_1   |     mod.load_ipython_extension(self.shell)
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django_extensions/management/notebook_extension.py", line 6, in load_ipython_extension
jupyter_1   |     style=no_style())
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django_extensions/management/shells.py", line 87, in import_objects
jupyter_1   |     setup()
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 17, in setup
jupyter_1   |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
jupyter_1   |     self._setup(name)
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
jupyter_1   |     self._wrapped = Settings(settings_module)
jupyter_1   |   File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 99, in __init__
jupyter_1   |     mod = importlib.import_module(self.SETTINGS_MODULE)
jupyter_1   |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
jupyter_1   |     return _bootstrap._gcd_import(name[level:], package, level)
jupyter_1   |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
jupyter_1   |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
jupyter_1   |   File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
jupyter_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
jupyter_1   |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
jupyter_1   |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
jupyter_1   |   File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
jupyter_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
jupyter_1   |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
jupyter_1   |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
jupyter_1   |   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
jupyter_1   | ImportError: No module named 'config'
```

**Comment by Narsail** [comment]
My real problem seems to be connected to the issue: https://github.com/ipython/ipython/issues/7062
