### ISSUE TITLE
pipchecker regression on 1.7.6 (AttributeError: 'Command' object has no attribute '_is_stable')

### ISSUE THREAD

**Issue by vstoykov** [django-extensions/django-extensions#1016]
When i upgrade to django-extensions 1.7.6 and try `manage.py pipchecker` I see the following error

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/path/to/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/to/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path/to/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/path/to/venv/lib/python2.7/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/path/to/venv/lib/python2.7/site-packages/django_extensions/management/commands/pipchecker.py", line 99, in handle
    self.check_pypi()
  File "/path/to/venv/lib/python2.7/site-packages/django_extensions/management/commands/pipchecker.py", line 136, in check_pypi
    available_version = self._available_version(dist_version, available)
  File "/path/to/venv/lib/python2.7/site-packages/django_extensions/management/commands/pipchecker.py", line 112, in _available_version
    if self._is_stable(dist_version):
AttributeError: 'Command' object has no attribute '_is_stable'
```

When I'm using django-extensions 1.7.5 everything works. I'm on Django 1.8.

**Comment by vstoykov** [comment]
This is duplicate of #1004. I see that it is fixed in master but will be good to release new version because latest version in PyPi is broken.

**Comment by trbs** [comment]
I'll try to get a new release out asap
