### ISSUE TITLE
`setup.py test` broken

### ISSUE THREAD

**Issue by DanLipsitt** [django-extensions/django-extensions#1029]
`setup.py test` doesn't work without `--pytest-args` arguments:

```
$ python setup.py test
running test
Searching for mock
Best match: mock 2.0.0
Processing mock-2.0.0-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/mock-2.0.0-py2.7.egg
Searching for pytest-cov
Best match: pytest-cov 2.4.0
Processing pytest_cov-2.4.0-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/pytest_cov-2.4.0-py2.7.egg
Searching for pytest-django
Best match: pytest-django 3.1.2
Processing pytest_django-3.1.2-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/pytest_django-3.1.2-py2.7.egg
Searching for python-dateutil
Best match: python-dateutil 2.6.0
Processing python_dateutil-2.6.0-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/python_dateutil-2.6.0-py2.7.egg
Searching for pbr>=0.11
Best match: pbr 2.0.0
Processing pbr-2.0.0-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/pbr-2.0.0-py2.7.egg
Searching for funcsigs>=1
Best match: funcsigs 1.0.2
Processing funcsigs-1.0.2-py2.7.egg

Using /Users/dan/src/django-extensions/.eggs/funcsigs-1.0.2-py2.7.egg
Searching for coverage>=3.7.1
Best match: coverage 4.3.4
Processing coverage-4.3.4-py2.7-macosx-10.8-x86_64.egg

Using /Users/dan/src/django-extensions/.eggs/coverage-4.3.4-py2.7-macosx-10.8-x86_64.egg
running egg_info
writing requirements to django_extensions.egg-info/requires.txt
writing django_extensions.egg-info/PKG-INFO
writing top-level names to django_extensions.egg-info/top_level.txt
writing dependency_links to django_extensions.egg-info/dependency_links.txt
reading manifest file 'django_extensions.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_extensions.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    'Topic :: Utilities',
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/dan/.virtualenvs/django-extensions/lib/python2.7/site-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "setup.py", line 33, in run_tests
    errno = pytest.main(shlex.split(self.pytest_args))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 124, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

This appears to be because `self.pytest_args` is initialized to an empty list in `setup.py` and then it's sent to `shlex` for parsing, but `shlex` doesn't handle lists. Defaulting to an empty string rather than a list allows tests to run, but many fail because the environment isn't set up correctly. Here's one example out of 42 test errors:

```
django_extensions/settings.py:9: in <module>
    add_replacements = getattr(settings, 'EXTENSIONS_REPLACEMENTS', {})
../../.virtualenvs/django-extensions/lib/python2.7/site-packages/django/conf/__init__.py:53: in __getattr__
    self._setup(name)
../../.virtualenvs/django-extensions/lib/python2.7/site-packages/django/conf/__init__.py:39: in _setup
    % (desc, ENVIRONMENT_VARIABLE))
E   ImproperlyConfigured: Requested setting EXTENSIONS_REPLACEMENTS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

`make test` works because it provides py.test arguments:

```
python setup.py test --pytest-args="tests django_extensions --ds=tests.testapp.settings --cov=django_extensions"
```

Any of those args that are required should be the default and user flags should be added to them (or perhaps override them).

**Comment by trbs** [comment]
a PR for this would be appreciated :)
