### ISSUE TITLE
passwd error

### ISSUE THREAD

**Issue by morenoh149** [django-extensions/django-extensions#1046]
I'm getting this error when trying out passwd
```
python manage.py passwd        
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File ".../lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File ".../lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File ".../lib/python2.7/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File ".../lib/python2.7/site-packages/django_extensions/management/commands/passwd.py", line 28, in handle
    u = User.objects.get(username=username)
  File ".../lib/python2.7/site-packages/softdelete/models.py", line 120, in get
    return self.all_with_deleted().get(*args, **kwargs)
  File ".../lib/python2.7/site-packages/django/db/models/query.py", line 378, in get
    clone = self.filter(*args, **kwargs)
  File ".../lib/python2.7/site-packages/django/db/models/query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File ".../lib/python2.7/site-packages/django/db/models/query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File ".../lib/python2.7/site-packages/django/db/models/sql/query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File ".../lib/python2.7/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File ".../lib/python2.7/site-packages/django/db/models/sql/query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File ".../lib/python2.7/site-packages/django/db/models/sql/query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File ".../env/pharmakon/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: account, created_at, ...
```

**Comment by trbs** [comment]
I think your using an old version of Django Extensions this was fixed back in Augustus 2016 in bbe325e26de19e54e92b5d94b03361c78a96a7ef

For the future please leave more details about your environment :)
