### ISSUE TITLE
Issues using export emails command

### ISSUE THREAD

**Issue by nicolasmendoza** [django-extensions/django-extensions#1065]
I found some bugs related working with export_emails command, using django-extensions 1.7.9, here a list of possible bugs:

1. 

>> **export_emails -f  vcard .** Doesn't work, fail using PY2x and PY3x.

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django_extensions/management/commands/export_emails.py", line 67, in handle
    getattr(self, options['format'])(qs, outfile)
  File "/home/nicolas/Projects/dummy/py35/lib/python3.5/site-packages/django_extensions/management/commands/export_emails.py", line 136, in vcard
    out.write(card.serialize().encode(self.encoding))
TypeError: write() argument must be str, not bytes
`

2. 

>> **export_emails -f linkedin  **   Works fine on PY2x, but in PY3x returns byte strings.
>> **export_emails -f google ** Same issue
>> **export_emails -f outlook ** Same issue

b'Mija\xc3\xadl',b'Bulgak\xc3\xb3v',b'mijail_bulgakov@gmail.com'
b'Gabriel Garcia',b'Marqu\xc3\xa9z',b'gabriel_marquez@gmail.com'
b'Fr\xc3\xa9d\xc3\xa9ric',b'Mistral',b'frederic_mistral@gmail.com'

3. #993 

I'll open a pull request that includes some code refactor, PY2/PY3 compatible, and 100% test coverage for this module.

**Comment by nicolasmendoza** [comment]
vcard format now is working for Python3.

**Comment by trbs** [comment]
Can we close this ticket as well ?

**Comment by nicolasmendoza** [comment]
Yes. Thanks @trbs
