### ISSUE TITLE
RandomCharField auto-populate?

### ISSUE THREAD

**Issue by nitrag** [django-extensions/django-extensions#1105]
I added `RandomCharField` to my model. 

1) Is it supposed to auto-populate?
2) If not, how can I force it to auto-populate?

```
from django_extensions.db.fields import RandomCharField

class Waypoint(models.Model):
    objectId = RandomCharField(length=9, unique=True, null=True, db_index=True)
```

From shell:
```
>>> import django_extensions
>>> RandomCharField(length=8, unique=True)
<django_extensions.db.fields.RandomCharField>
```

```
>>> from django_extensions.db.fields import RandomCharField
>>> from features.models import Waypoint
>>> qs = Waypoint.objects.all()
>>> print qs.first()

>>> first = qs.first()
>>> first.geom
<Point object at 0x111e04eb0>
>>> first.objectId = RandomCharField(length=9, unique=True)
>>> first.objectId
<django_extensions.db.fields.RandomCharField>
>>> first.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ryan/Documents/Offroad/django/offroad-django/beanstalk-project/features/models.py", line 268, in save
    super(Waypoint, self).save(*args, **kwargs)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/base.py", line 905, in _save_table
    forced_update)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/base.py", line 955, in _do_update
    return filtered._update(values) > 0
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1199, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/ryan/Documents/Offroad/django/offroad-django/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
DataError: value too long for type character varying(9)
```

Query is trying to do this:
`UPDATE "features_waypoint" SET "trail_id" = \'4ZvuEuu8Jy\', "objectId" = \'<django_extensions.db.fields.RandomCharField>\', "name" = \'\', `

**Comment by mehmir** [comment]
Any Idea?
