### ISSUE TITLE
The version of pyparsing in docs will fail with Python 3.6.2

### ISSUE THREAD

**Issue by EmadMokhtar** [django-extensions/django-extensions#1106]
I have an environment with Python 3.6.2 and I tried to install pyparsing version 1.5.7 as [documentation](https://django-extensions.readthedocs.io/en/latest/graph_models.html#selecting-a-library) mentioned, and it failed because of the old style of catching exceptions in the code.

Please update the documentation.

**Comment by trbs** [comment]
Thanks for the report !

Could you please write a test for this ? 

Then we can fix the documentation and be sure we catch future problems with it as well.

**Comment by shangdahao** [comment]
This is because pyparsing==1.5.7 don't support python3.

For python3, we need pyparsing>=2.0.

I am wondering do we need a test for this?

**Comment by phalt** [comment]
This means that the django_extensions `graph_models` does not work with python 3.6.2 or greater, even though the docs say to use this version explicitly:

https://github.com/django-extensions/django-extensions/blob/8b6ed70cd84365b3860cf3f662ae5ef243546398/docs/graph_models.rst

(Bottom of "selecting a library" section)

```
python manage.py graph_models --pydot -a -g -o my_project_visualized.png
Traceback (most recent call last):
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/pydot.py", line 1861, in create
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django_extensions/management/commands/graph_models.py", line 193, in handle
    self.render_output_pydot(dotdata, **options)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/django_extensions/management/commands/graph_models.py", line 255, in render_output_pydot
    graph.write(output_file, format=format)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "/Users/phalt/Envs/my_project/lib/python3.6/site-packages/pydot.py", line 1867, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.
```

```
python --version
>> Python 3.6.5
```
Packages:
```
Django==2.0.7
django-extensions==2.1.0
pyparsing==2.2.0
pydot==1.2.4
```

**Comment by VishnuPy** [comment]
python --version
>> Python 3.6.5
pyparsing==2.2.0

Sublime Text 3 throws error when trying to import matplotlib.pyplot as plt. 
Error is:
Traceback (most recent call last):
  File "D:\Vishnu\Personal\Learning\Data Science\Python\Sublime_Reports\CatsVSDogs_sublime_Graph.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "My Python folder \Python36\site-packages\matplotlib\__init__.py", line 130, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "C:\Users\VishnuVV\AppData\Roaming\Python\Python36\site-packages\matplotlib\rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "C:\Users\VishnuVV\AppData\Roaming\Python\Python36\site-packages\matplotlib\fontconfig_pattern.py", line 22, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
ModuleNotFoundError: No module named 'pyparsing'
[Finished in 1.7s]
Then tried to find the resolution and came across Pyparsing PKG-INFO file in which the support list stopped with Python 3.5. 
Does it mean that anything.

I am not able to use sublime text for graphs as not able to import matplotlib.
Help would be much appreciated.

**Comment by trbs** [comment]
This has been resolved in: https://github.com/django-extensions/django-extensions/commit/22ccf799a582c0c43ad3dbb451935a0ab5c5e3e1

**Comment by bmyrtil-fwl** [comment]
Has this been resolved? I am getting the exact same error

**Comment by trbs** [comment]
Afaik. Other then Travis tests I do not use or test with Windows or older versions of Python. Happy to accept a PR with test for any further fixes or have the work sponsored.
