### ISSUE TITLE
show_urls is broken

### ISSUE THREAD

**Issue by flip111** [django-extensions/django-extensions#1130]
i just install python3.5 and django2 in a virtualenv and i follow the installation instruction for django-extensions. Then when i try `python manage.py show_urls` i get this error

```
» python manage.py show_urls
Traceback (most recent call last):
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django_extensions/management/commands/show_urls.py", line 11, in <module>
    from django.urls import RegexURLPattern, RegexURLResolver, LocaleRegexURLResolver
ImportError: cannot import name 'RegexURLPattern'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/flip111/python/python-django-crud/venv2/lib/python3.5/site-packages/django_extensions/management/commands/show_urls.py", line 13, in <module>
    from django.core.urlresolvers import RegexURLPattern, RegexURLResolver, LocaleRegexURLResolver
ImportError: No module named 'django.core.urlresolvers'
```

**Comment by trbs** [comment]
Please try again with git master
