### ISSUE TITLE
command notes, IndexError: list index out of range

### ISSUE THREAD

**Issue by tpywao** [django-extensions/django-extensions#1187]
- Python 3.6.1
- Django: 2.0.3
- django-extensions: 2.0.6

I use only Django ORM, and didn't set `settings.TEMPLATES`.
Cause this Error.

```
$ python manage.py notes
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "{INSTALLED_PATH}/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "{INSTALLED_PATH}/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "{INSTALLED_PATH}/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "{INSTALLED_PATH}/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "{INSTALLED_PATH}/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "{INSTALLED_PATH}/django_extensions/management/commands/notes.py", line 26, in handle
    template_dirs = get_template_setting('DIRS', [])
  File "{INSTALLED_PATH}/django_extensions/compat.py", line 44, in get_template_setting
    if templates_var is not None and template_key in templates_var[0]:
IndexError: list index out of range
```

I fixed `django_extensions/compat.py`. It executable.

```diff
- if templates_var is not None and template_key in templates_var[0]:
+ if templates_var and template_key in templates_var[0]:
```

Thank you!

**Comment by trbs** [comment]
Fix is commited to master. Added simple test (and a regression test) for `notes` and also updated `django_extensions/compat.py` to not error out in this case.

Please test, if it does not fix it properly please reopen the ticket.

Thanks !

**Comment by tpywao** [comment]
It works! Thank you!
