### ISSUE TITLE
import error on typing.Type for python 3.5.0 

### ISSUE THREAD

**Issue by rcdosado** [django-extensions/django-extensions#1188]
im using django-extensions 2.0.6, OS is windows 7, python 3.5.0, django 1.11.3
an import error occurs after i execute `python manage.py shell_plus` pointing me to this line from shells.py & import_subclasses.py :
> from typing import (  # NOQA
>         Dict,
>         List,
>         Tuple,
>         Type,
>         Union,
> )

current workaround is changing that to:
> if False:
>     from typing import (  # NOQA
>         Dict,
>         List,
>         Tuple,
>         Type,
>         Union,
>     )

for both shells.py, and import_subclasses.py

**Comment by trbs** [comment]
Please give more information such as the exact error. The builds are passing on `Python 3.5` so I'm not sure why this would give an error for you.

**Comment by rcdosado** [comment]
when i execute the command `python manage.py shell_plus` i get this error on my terminal, although the error points only to django_extensions\management\shells.py, django_extensions\import_subclasses.py also is triggered with the same error. 
> Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_
line
    utility.execute()
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django\core\management\__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django\core\management\__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "c:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django_extensions\management\commands\shell_plus.py", line 14, in <modu
le>
    from django_extensions.management.shells import import_objects
  File "c:\MS2017\CIS201M\projects\env35\lib\site-packages\django_extensions\management\shells.py", line 9, in <module>
    from typing import (  # NOQA
ImportError: cannot import name 'Type'

**Comment by trbs** [comment]
Thanks for reporting the issue.

Please check if you do not have by any change a broken setup. Maybe you have another module called `typing` on your Python path ?

Python 3.5 comes with the `typing` module which includes the `Type` class: https://github.com/python/cpython/blob/3.5/Lib/typing.py#L2092

If this is not the case and it is an error in `django-extensions` please reopen the issue and attach a reproducible test case.

**Comment by wilblack** [comment]
hi @trbs. The error output I get is the same as what @rcdosado reported. As for a test case, I get the error when I run `python manage.py shell_plus`.

Here is what I get when I try to import Type directly:

```
(venv)wilblack@Wils-MacBook-Pro api (feature/start-api) $ ./manage.py shell
Python 3.5.1 (default, Jan 22 2016, 08:52:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import typing

In [2]: typing.__file__
Out[2]: '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py'

In [3]: typing.Type
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-d9720ca0b34f> in <module>()
----> 1 typing.Type

AttributeError: module 'typing' has no attribute 'Type'

```

It appears that `Type` is not in fact a valid attribute of typing. In the link you posted it has a strange comment on the class to not use it outside of annotations. Could that have something to do with it?

```
# This is not a real generic class.  Don't use outside annotations.
class Type(Generic[CT_co], extra=type):
    """A special construct usable to annotate class objects.
```

**Comment by OxInsky1105** [comment]
decreasing the version scipy to 1.2.1 which can run it！not the python 3.5.1 or typing。

**Comment by OxInsky1105** [comment]
decrease the version of scipy or (defected moudle)to 1.2.1  and uninstall typing. it can works
