### ISSUE TITLE
pipchecker not compatible with pip 10.0.0

### ISSUE THREAD

**Issue by picturedots** [django-extensions/django-extensions#1195]
After upgrading to pip 10.0.0 I now get the following exception, due to changes in pip internals in version 10:

```
# manage.py pipchecker
Traceback (most recent call last):
  File "/code/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_extensions/management/commands/pipchecker.py", line 9, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

It looks like the import should now be `from pip._internal.req.req_file import parse_requirements`

**Comment by picturedots** [comment]
There were a bunch of changes besides the first exception -- I have a working fix and will make a pull request.

**Comment by trbs** [comment]
Thanks for the PR !
