### ISSUE TITLE
TransactionManagementError with syncdata management command

### ISSUE THREAD

**Issue by Apreche** [django-extensions/django-extensions#1215]
I'm running django-extensions 2.0.7, Django 2.0.5 and Python 3.5.2. 

When I run the command `./manage.py syncdata` I see this error:

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django_extensions/management/commands/syncdata.py", line 190, in handle
    transaction.commit()
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/db/transaction.py", line 35, in commit
    get_connection(using).commit()
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 260, in commit
    self.validate_no_atomic_block()
  File "/home/myuser/.virtualenvs/myproject/lib/python3.5/site-packages/django/db/backends/base/base.py", line 432, in validate_no_atomic_block
    "This is forbidden when an 'atomic' block is active.")
django.db.transaction.TransactionManagementError: This is forbidden when an 'atomic' block is active.
```

**Comment by trbs** [comment]
Please test with ffbda59286fb40c91dd3a7cc1c5b60fae0ac3a8d

**Comment by trbs** [comment]
please reopen if it does not fix the issue.

if it does work i'll make a new release as soon as I can.

**Comment by greyhare** [comment]
There's still a `transaction.rollback()` on line 173 of `syncdata.py`. It can probably be deleted.

**Comment by MattFisher** [comment]
@trbs The `transaction.rollback()` that @greyhare pointed out causes `syncdata` to fail silently if there's a `DeserializationError`.

In our case, an old field that had been removed from a model caused only 193 of the 309 objects in our fixture to be loaded, with no error messages even with `--traceback`.

Removing the `rollback` line showed the errors correctly.

**Comment by trbs** [comment]
Could you please make a PR with a test, such that we have a regression test for this ?

**Comment by MattFisher** [comment]
Raised #1532 1532
