### ISSUE TITLE
TypeError: 'str' does not support the buffer interface in get_slug_fields() - AutoSlugField

### ISSUE THREAD

**Issue by behconsci** [django-extensions/django-extensions#1235]
![image](https://user-images.githubusercontent.com/10358323/43830576-e6f56dde-9b01-11e8-920b-b22dfe0e65ee.png)

I am using 

vagrant
python3.4. 
django 1.11

I tried with all django-extension versions starting from 1.9.9.

**Comment by trbs** [comment]
Just from quickly looking a fix does not spring to mind :-(

Would it be possible to create a test case for this ? or otherwise reproducable example ?
This makes it easier for somebody to pick it up...

**Comment by behconsci** [comment]
ok it was something else. sorry

**Comment by trbs** [comment]
No problem, happy you solved it 👍

**Comment by behconsci** [comment]
@trbs Sorry but I have to open this issue again :/ I just can not resolve it. 

with version 1.7.7 and django 1.11 und python 3.4, this is my code:

```
from django_extensions.db.models import TitleSlugDescriptionModel, TimeStampedModel

@python_2_unicode_compatible
class MyModel(TitleSlugDescriptionModel, TimeStampedModel): 
    # fields 
```

this is the whole error traceback: 

```
    goldmarie: Traceback (most recent call last):
    goldmarie:   File "/home/vagrant/goldmarie/shops/congstar/migrations/0001_initial.py", line 16, in create_shop
    goldmarie:     GoldmarieShop.objects.using(db_alias).get(shop_code=SHOP_CODE)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/query.py", line 379, in get
    goldmarie:     self.model._meta.object_name
    goldmarie: __fake__.DoesNotExist: GoldmarieShop matching query does not exist.
    goldmarie: 
    goldmarie: During handling of the above exception, another exception occurred:
    goldmarie: 
    goldmarie: Traceback (most recent call last):
    goldmarie:   File "./manage.py", line 10, in <module>
    goldmarie:     execute_from_command_line(sys.argv)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    goldmarie:     utility.execute()
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
    goldmarie:     self.fetch_command(subcommand).run_from_argv(self.argv)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    goldmarie:     self.execute(*args, **cmd_options)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    goldmarie:     output = self.handle(*args, **options)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    goldmarie:     fake_initial=fake_initial,
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/migrations/executor.py", line 115, in migrate
    goldmarie:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    goldmarie:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    goldmarie:     state = migration.apply(state, schema_editor)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/migrations/migration.py", line 129, in apply
    goldmarie:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    goldmarie:     self.code(from_state.apps, schema_editor)
    goldmarie:   File "/home/vagrant/goldmarie/shops/congstar/migrations/0001_initial.py", line 31, in create_shop
    goldmarie:     m2n_model_name='congstar.CongstarUserOrder'
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/query.py", line 393, in create
    goldmarie:     obj.save(force_insert=True, using=self.db)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/base.py", line 806, in save
    goldmarie:     force_update=force_update, update_fields=update_fields)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/base.py", line 836, in save_base
    goldmarie:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/base.py", line 922, in _save_table
    goldmarie:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/base.py", line 961, in _do_insert
    goldmarie:     using=using, raw=raw)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/manager.py", line 85, in manager_method
    goldmarie:     return getattr(self.get_queryset(), name)(*args, **kwargs)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/query.py", line 1060, in _insert
    goldmarie:     return query.get_compiler(using=using).execute_sql(return_id)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    goldmarie:     for sql, params in self.as_sql():
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    goldmarie:     for obj in self.query.objs
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1051, in <listcomp>
    goldmarie:     for obj in self.query.objs
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1050, in <listcomp>
    goldmarie:     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1000, in pre_save_val
    goldmarie:     return field.pre_save(obj, add=True)
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django_extensions/db/fields/__init__.py", line 179, in pre_save
    goldmarie:     value = force_text(self.create_slug(model_instance, add))
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django_extensions/db/fields/__init__.py", line 154, in create_slug
    goldmarie:     slug = self.separator.join(map(slug_for_field, self._populate_from))
    goldmarie:   File "/home/vagrant/.virtualenvs/goldmarie/lib/python3.4/site-packages/django_extensions/db/fields/__init__.py", line 153, in <lambda>
    goldmarie:     slug_for_field = lambda field: self.slugify_func(getattr(model_instance, field))
    goldmarie: TypeError: getattr(): attribute name must be string
```

**Comment by behconsci** [comment]
I made print here: 
![image](https://user-images.githubusercontent.com/10358323/43890778-f4aca4a8-9bc7-11e8-8d69-f653c23e00a6.png)

and got this:
![image](https://user-images.githubusercontent.com/10358323/43890795-02969ce0-9bc8-11e8-993f-8c248eb5d582.png)

so, "field" is a tuple, not string. how can this be? I am passing a string in my create query as you see above.

**Comment by behconsci** [comment]
ok, I found out that it it turning the string into byte string and hitting the error: 

![image](https://user-images.githubusercontent.com/10358323/43892062-3e255942-9bcb-11e8-8570-efca0aae8065.png)

**Comment by behconsci** [comment]
Ok, the issue is fixed when I upgraded to 2.0.3.

**Comment by behconsci** [comment]
![image](https://user-images.githubusercontent.com/10358323/43901950-0f75e936-9be9-11e8-8421-2d9fef26dfa0.png)

with python3.5, django 1.11 and extensions 2.0.7 I am getting this error. any ideas? :/

**Comment by behconsci** [comment]
now I found out that LOOKUP_SEP which is imported from django.db.models.constants is a str. 

it is failing here: 

```
lookup_value_path = lookup_value.split(LOOKUP_SEP)
````

**Comment by behconsci** [comment]
@trbs I solved it by adding these line to extensions code: 

![image](https://user-images.githubusercontent.com/10358323/44019450-1e452596-9edf-11e8-8683-0f381b1ace7f.png)

do you think, it makes sense to make a PR?

**Comment by trbs** [comment]
@behconsci think probably breaks a lot of other code :-)

The different error message I think is because of the different Python versions... they made the error a bit clearer in Python 3.5 onwards.

`lookup_value` is expected to be a `string` not `bytes`, doing the decode in the second line makes it all strings again. So instead of encoding `LOOKUP_SEP` might as well just decoded `lookup_value` I think.

Not entirely sure from the code you pasted why `lookup_value` is apparently bytes there.

From your example it should be relatively easy to make a test in our test suite. Using basically the code you outlined above. Could you please make a PR with that ?

That makes it a lot easier to debug to the root cause and accept a PR to fix it, as well as making sure we don't regress later :-)

**Comment by behconsci** [comment]
@trbs you are right. I will do it that way and make a PR. thnx for the
feedback

trbs <notifications@github.com> schrieb am Mo. 13. Aug. 2018 um 18:07:

**Comment by behconsci** [comment]
@trbs I can't push the new branch to the repo, do you know why? 

![image](https://user-images.githubusercontent.com/10358323/44077999-b8b100c0-9fa5-11e8-8fcc-f20586e266c9.png)

i tried with both ssh and https origins

**Comment by behconsci** [comment]
@trbs can't push the new branch to the repo :/ 

![image](https://user-images.githubusercontent.com/10358323/44078339-7f8bb514-9fa6-11e8-89a6-ac6ff540a46c.png)

am I missing something?

**Comment by behconsci** [comment]
@trbs created the PR
https://github.com/django-extensions/django-extensions/pull/1237

thnx

**Comment by trbs** [comment]
Thanks for the PR. 
As commented on the PR itself why use `bytes` for the `populate_from` attribute ? I don't see the use case for that. (maybe I'm missing something here ?)

Think that needs to be a `str` anyways since it references the model field. If that's the case is there a problem left ? Guess we can update the code to check if users use the wrong type and have a clearer error message...

**Comment by behconsci** [comment]
ok the problem was that developers befor me had hardcoded some bytestrings into migrations. i close the issue and pr
