### ISSUE TITLE
runserver_plus shows wrong traceback if using any function-based middlewares

### ISSUE THREAD

**Issue by MattFisher** [django-extensions/django-extensions#1273]
When using `runserver_plus` with function-based middlewares configured, exceptions are not being shown correctly in the browser. All exceptions show up as `builtins.KeyError  KeyError: 'self'`.

The stack trace displayed in the browser varies, and sometimes shows the correct trace, but still shows the wrong error message `KeyError: 'self'`.

Investigating the stack trace being logged by the server shows many repeats of the following:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[env]/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "[my_project]/common/middleware.py", line 105, in middleware
    response = get_response(request)
  File "[env]/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "[env]/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "[env]/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "[env]/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 28, in null_technical_500_response
    if isinstance(tb.tb_next.tb_frame.f_locals['self'], WSGIHandler):
KeyError: 'self'
```

This is happening because when `null_technical_500_response` is executed for each middleware, it's expecting to find `'self'` in `tb.tb_next.tb_frame.f_locals`, but if the middleware is function-based (as in the [first example in the docs](https://docs.djangoproject.com/en/2.1/topics/http/middleware/#writing-your-own-middleware)), there is no `self`, causing the `KeyError`.

Modifying the line `if isinstance(tb.tb_next.tb_frame.f_locals['self'], WSGIHandler):` to `if isinstance(tb.tb_next.tb_frame.f_locals.get('self'), WSGIHandler):` solves the problem.

**Comment by browniebroke** [comment]
This is released in `django-extensions` 2.1.4+ so I think this can be closed.
