### ISSUE TITLE
sqldiff throws exception in 2.1.4

### ISSUE THREAD

**Issue by tisdall** [django-extensions/django-extensions#1275]
This is using Django 1.11.16, Python 2, and django-extensions 2.1.4
```
# python manage.py sqldiff -a
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 1265, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 1252, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 1245, in handle
    sqldiff_instance.find_differences()
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 659, in find_differences
    self.find_unique_missing_in_db(meta, table_indexes, table_constraints, table_name)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 416, in find_unique_missing_in_db
    index_name = schema_editor._create_index_name(table_name, unique_columns)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 877, in _create_index_name
    _, table_name = split_identifier(model._meta.db_table)
AttributeError: 'unicode' object has no attribute '_meta'
```

**Comment by GertBurger** [comment]
This is still a problem in 2.1.6

**Comment by trbs** [comment]
Can somebody provide a PR with a test case for this ?

**Comment by tisdall** [comment]
I don't have a PR, but after a little digging it seems that the issue is a change in `_create_index_name`.  In Django 1.11 and earlier the interface is `_create_index_name(model, column_names, suffix="")` while in 2.0 and after it's `_create_index_name(table_name, column_names, suffix="")`.  The former is expecting a model object and then tries to access the `._meta` property on it while the latter is expecting a string (which is what sqldiff is passing it).  So it seems `sqldiff` dropped support for 1.11 prematurely.
