### ISSUE TITLE
graph_models with '-I' arg - error

### ISSUE THREAD

**Issue by lboc80** [django-extensions/django-extensions#1289]
I'd like to include only few models for my app but I get an error:
```
(my_env) ➜  project_root (feature/certs-db-restruct) ✗ python manage.py graph_models my_app -E -n -I CompanyUserProfile,Event -o /tmp/abs_data_comp__.png --settings=config.settings.local
Error: syntax error in line 313 near '&'
Traceback (most recent call last):
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1226, in read
    self.handle = gv.agread(fh, None)
ValueError: agread: bad input data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django_extensions/management/commands/graph_models.py", line 165, in handle
    self.render_output_pygraphviz(dotdata, **options)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/django_extensions/management/commands/graph_models.py", line 203, in render_output_pygraphviz
    graph = pygraphviz.AGraph(dotdata)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/pygraphviz/agraph.py", line 168, in __init__
    self.from_string(string)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1307, in from_string
    self.read(fh)
  File "/Users/llbb/venvs/my_env/lib/python3.6/site-packages/pygraphviz/agraph.py", line 1228, in read
    raise DotError("Invalid Input")
pygraphviz.agraph.DotError: Invalid Input
```
anybody has experiences the same?
without the '-I' args it works fine.
```
Python version: 3.6.4
Django version: 1.11.15
pygraphviz version: 1.5
```

Thanks

**Comment by trbs** [comment]
Do you think it's possible to create a reproducible example or even a test case for this ?

**Comment by lboc80** [comment]
@trbs tnx for the reply.
How? the only way that comes to my mind in order to let you reproduce it is to have the same db schema that I have, hence you'll need a db dump (schema only).
I forgot to mention since I thought wasn't  important for this: i'm using `postgresql 9.6.8` as db backend.
is that what you want?

**Comment by lboc80** [comment]
@trbs well not really....you'll probably need the models.py files and the project layout....

**Comment by trbs** [comment]
Seems like we are generating invalid dot output, but that can be very hard to test if the problem can't be reproduced. In this case I guess once anybody build a (stand alone) reproducible you probably also found the error at the same time :-)
