### ISSUE TITLE
python setup.py test fails

### ISSUE THREAD

**Issue by jayvdb** [django-extensions/django-extensions#1307]
```
+ /usr/bin/python2 setup.py test
[   41s] running test
[   41s] running egg_info
[   41s] writing requirements to django_extensions.egg-info/requires.txt
[   41s] writing django_extensions.egg-info/PKG-INFO
[   41s] writing top-level names to django_extensions.egg-info/top_level.txt
[   41s] writing dependency_links to django_extensions.egg-info/dependency_links.txt
[   41s] reading manifest file 'django_extensions.egg-info/SOURCES.txt'
[   41s] reading manifest template 'MANIFEST.in'
[   41s] writing manifest file 'django_extensions.egg-info/SOURCES.txt'
[   41s] running build_ext
[   41s] Traceback (most recent call last):
[   41s]   File "setup.py", line 103, in <module>
[   41s]     'Topic :: Utilities',
[   41s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
[   41s]     return distutils.core.setup(**attrs)
[   41s]   File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
[   42s]     dist.run_commands()
[   42s]   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
[   42s]     self.run_command(cmd)
[   42s]   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
[   42s]     cmd_obj.run()
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 228, in run
[   42s]     self.run_tests()
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 250, in run_tests
[   42s]     exit=False,
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
[   42s]     self.parseArgs(argv)
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
[   42s]     self.createTests()
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
[   42s]     self.module)
[   42s]   File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
[   42s]     suites = [self.loadTestsFromName(name, module) for name in names]
[   42s]   File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
[   42s]     module = __import__('.'.join(parts_copy))
[   42s] ImportError: No module named run_tests
[   42s] error: Bad exit status from /var/tmp/rpm-tmp.22Y8C8 (%check)
```

run_tests.py was previously reported missing at https://github.com/django-extensions/django-extensions/issues/423 and https://github.com/django-extensions/django-extensions/issues/1029

Using pytest also doesnt work

```
+ /usr/bin/python2 -m pytest
[   40s] ============================= test session starts ==============================
[   40s] platform linux2 -- Python 2.7.15, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
[   40s] rootdir: /home/abuild/rpmbuild/BUILD/django-extensions-1.2.2, inifile:
[   40s] plugins: django-3.4.4
[   42s] collected 0 items / 2 errors
[   42s]
[   42s] ==================================== ERRORS ====================================
[   42s]  ERROR collecting _build.python3/lib/django_extensions/tests/test_dumpscript.py
[   42s] _build.python3/lib/django_extensions/tests/test_dumpscript.py:13: in <module>
[   42s]     from django_extensions.tests.models import Name, Note, Person
[   42s] _build.python3/lib/django_extensions/tests/models.py:4: in <module>
[   42s]     class Secret(models.Model):
[   42s] _build.python3/lib/django_extensions/tests/models.py:5: in Secret
[   42s]     name = models.CharField(blank=True, max_length=255, null=True)
[   42s] /usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1061: in __init__
[   42s]     super(CharField, self).__init__(*args, **kwargs)
[   42s] /usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py:172: in __init__
[   42s]     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
[   42s] /usr/lib/python2.7/site-packages/django/conf/__init__.py:56: in __getattr__
[   42s]     self._setup(name)
[   42s] /usr/lib/python2.7/site-packages/django/conf/__init__.py:39: in _setup
[   42s]     % (desc, ENVIRONMENT_VARIABLE))
[   42s] E   ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[   42s] _________ ERROR collecting django_extensions/tests/test_dumpscript.py __________
[   42s] /usr/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
[   42s]     __import__(modname)
[   42s] _build.python3/lib/django_extensions/tests/__init__.py:2: in <module>
[   42s]     from django_extensions.tests.test_dumpscript import DumpScriptTests
[   42s] /usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:294: in load_module
[   42s]     six.exec_(co, mod.__dict__)
[   42s] /usr/lib/python2.7/site-packages/six.py:709: in exec_
[   42s]     exec("""exec _code_ in _globs_, _locs_""")
[   42s] <string>:1: in <module>
[   42s]     ???
[   42s] _build.python3/lib/django_extensions/tests/test_dumpscript.py:13: in <module>
[   42s]     from django_extensions.tests.models import Name, Note, Person
[   42s] _build.python3/lib/django_extensions/tests/models.py:4: in <module>
[   42s]     class Secret(models.Model):
[   42s] _build.python3/lib/django_extensions/tests/models.py:5: in Secret
[   42s]     name = models.CharField(blank=True, max_length=255, null=True)
[   42s] /usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1061: in __init__
[   42s]     super(CharField, self).__init__(*args, **kwargs)
[   42s] /usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py:172: in __init__
[   42s]     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
[   42s] /usr/lib/python2.7/site-packages/django/conf/__init__.py:56: in __getattr__
[   42s]     self._setup(name)
[   42s] /usr/lib/python2.7/site-packages/django/conf/__init__.py:39: in _setup
[   42s]     % (desc, ENVIRONMENT_VARIABLE))
[   42s] E   ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

In any case, the `tests` are missing from the source tarball, so that also needs addressing for distro packaging.

**Comment by trbs** [comment]
Which version of Django-extensions are you using ? In the output it says 1.2.2 does the problem also exists in master or the latest release ?

**Comment by jayvdb** [comment]
Doesnt matter.  It isnt included in the sdists being published.  Usually fixed by adding them to `MANIFEST.in`.

```console
> ls */
django-extensions-1.2.2/:
django_extensions  django_extensions.egg-info  docs  LICENSE  MANIFEST.in  PKG-INFO  README.rst  setup.cfg  setup.py

django-extensions-2.1.5/:
django_extensions  django_extensions.egg-info  docs  LICENSE  MANIFEST.in  PKG-INFO  README.rst  setup.cfg  setup.py  tox.ini
```

**Comment by trbs** [comment]
Could you submit a PR for this ?

I assume it's as simple as adding `recursive-include tests *` but it would be good if you could test it at the same time :-)
