### ISSUE TITLE
2.1.5 TemplateDoesNotExist

### ISSUE THREAD

**Issue by eazaika** [django-extensions/django-extensions#1327]
I got a bad traceback by tried to use foreignkey_searchinput.html
```
2019-02-27 10:21:45,535 WARNING 59512 [django.template] loader_tags.py:232 - Exception raised while rendering {% include %} for template 'unknown'. Empty string rendered instead.
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/html.py", line 385, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 127, in as_widget
    **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/forms/widgets.py", line 220, in render
    context = self.get_context(name, value, attrs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py", line 282, in get_context
    'rendered_widget': self.widget.render(name, value, attrs),
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django_extensions/admin/widgets.py", line 85, in render
    ), context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader.py", line 65, in render_to_string
    template = select_template(template_name, using=using)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: django_extensions/widgets/auth/user/foreignkey_searchinput.html, django_extensions/widgets/auth/foreignkey_searchinput.html, django_extensions/widgets/foreignkey_searchinput.html
```
The template is in the system
```
ls -la /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages/django_extensions/templates/django_extensions/widgets/foreignkey_searchinput.html
-rw-r--r-- 1 root root 2044 фев 21 13:47 /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages/django_extensions/templates/django_extensions/widgets/foreignkey_searchinput.html
```
What's up?

**Comment by trbs** [comment]
Not sure, by the looks of it it should work ?
Could try to see if you can manually load the template in `shell` / `shell_plus` and see if the template loader settings might prevent your system from finding them ?

Otherwise try with a fresh virtualenv and django project, that way you can eliminate if this has anything to do with your local or project setup.

If it turns out to be a bug inside `django-extensions` please feel free to reopen this issue.
