### ISSUE TITLE
runprofileserver: AttributeError: module 'django.utils.autoreload' has no attribute 'main'

### ISSUE THREAD

**Issue by thacoon** [django-extensions/django-extensions#1376]
When running `python manage.py runprofileserver --use-cprofile --prof-path=/tmp/django-profile` with `django==2.2.1` and `django-extensions==2.1.7` I get the following error:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/user/.virtualenvs/whoMoves/lib/python3.7/site-packages/django_extensions/management/commands/runprofileserver.py", line 287, in handle
    autoreload.main(inner_run)
AttributeError: module 'django.utils.autoreload' has no attribute 'main'
```

**Comment by trbs** [comment]
Thanks for reporting !

I've committed a patch for this error. Could you please check with the git master version ?
If problem persist please re-open this ticket.

**Comment by thacoon** [comment]
Works now. Thanks :)

**Comment by trbs** [comment]
Awesome, let me try to get a new release out on PyPI today as well
