### ISSUE TITLE
AttributeError: module 'django.utils.autoreload' has no attribute 'main'

### ISSUE THREAD

**Issue by chenzx** [django-extensions/django-extensions#1382]
I'm using django-extensions to do profiling with a django-2.2.2 app on Python-3.7.3, i'm getting the errors:

'''
(python3.7.3) D:\repo\webapp_backend>python manage.py runprofileserver --us
e-cprofile --prof-path=d:/django-profile
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\ENV\python3.7.3\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\ENV\python3.7.3\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\ENV\python3.7.3\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\ENV\python3.7.3\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "D:\ENV\python3.7.3\lib\site-packages\django_extensions\management\utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "D:\ENV\python3.7.3\lib\site-packages\django_extensions\management\commands\runprofileserver.py", line 287, in handle
    autoreload.main(inner_run)
AttributeError: module 'django.utils.autoreload' has no attribute 'main'
'''

**Comment by trbs** [comment]
Think this was fixed in the latest version.

Please try with the latest version of django-extensions, specifically a version with this patch https://github.com/django-extensions/django-extensions/commit/1c69d9ec00e49c9a6604cf0fb09ebc8515cff76d

If it still does not does not work please reopen the issue.
