### ISSUE TITLE
shell_plus --notebook -> "Cannot mix str and non-str arguments"

### ISSUE THREAD

**Issue by Moulde** [django-extensions/django-extensions#1413]
I get the following exception when trying to run the notebook.
But the parameters passed to the notebook is not visible.

I got the error, and then added the `--no-browser` argument, as i thought that the below error was because it was trying to build some url to open the browser, i'm running it in a docker container, but adding the argument did not change the exception.

Arguments
```
NOTEBOOK_ARGUMENTS = [
    '--no-browser',
    '--allow-root',
    '--ip', '0.0.0.0',
    '--port', '4500',
]
```

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 112, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 521, in handle
    shell()
  File "/usr/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 244, in run_notebook
    app.start()
  File "/usr/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 1794, in start
    '    %s' % urljoin('file:', pathname2url(self.browser_open_file)),
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

Have anyone seen this issue before?

**Comment by trbs** [comment]
Seems to have something todo with the version of the notebook software and python 2.x. and maybe not django-extensions ?

(If for some reason this is a bug in our project, please provide a test case in a PR)
