### ISSUE TITLE
Please tell me what can i do to resolve this problem? check_migrations

### ISSUE THREAD

**Issue by lvshuai789** [django-extensions/django-extensions#1415]
[root@iZ25qp2d64mZ EHT]# python3 manage.py runserver_plus --cert server.crt 127.0.0.1:7000
Traceback (most recent call last):
File "manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.5/site-packages/django/core/management/init.py", line 338, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.5/site-packages/django/core/management/init.py", line 330, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 390, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 441, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.5/site-packages/django_extensions/management/utils.py", line 62, in inner
ret = func(self, *args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runserver_plus.py", line 262, in handle
self.inner_run(options)
File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/runserver_plus.py", line 305, in inner_run
self.check_migrations()
AttributeError: 'Command' object has no attribute 'check_migrations'

**Comment by trbs** [comment]
@lvshuai789 we already answered your question in https://github.com/django-extensions/django-extensions/issues/1414

Please stop creating new issues and upgrade your `Django` version.
