### ISSUE TITLE
No module named 'django-extensions' on Django 3.x

### ISSUE THREAD

**Issue by martinvol** [django-extensions/django-extensions#1459]
Pipenv file:
```
django = "==3.0.2"
django-extensions = "==2.2.5"
```

settings.py
```
import os
import django_extensions
(...)
INSTALLED_APPS = [
    '...',
    'django-extensions'
]
```

When running:
```
$ pipenv run python manage_django.py shell
Traceback (most recent call last):
  File "manage_django.py", line 21, in <module>
    main()
  File "manage_django.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/martinvol/.local/share/virtualenvs/project-ue1Dk_mJ/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-extensions'
```

Please note that the import inside `settings.py` doesn't fail.

**Comment by trbs** [comment]
it's `django_extensions` not `django-extensions` :-)

**Comment by martinvol** [comment]
🤦‍♂️

**Comment by WafaaAlhussain** [comment]
I had the same error even with writing django_extensions inside INSTALLED_APPS, @trbs  do you how can I fix it?

**Comment by romulo-mesquita** [comment]
**I have the same problem but in my configuration the name is right 'django_extensions'.**

env/bin/python manage.py graph_models --pygraphviz -a -g -o meu_diagrama.png
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/romulo/Sistemas/dashboard_google_V2/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'

**Comment by WafaaAlhussain** [comment]
@romulo-mesquita  It was fixed for me by reinstalling django_extensions from the requirements.txt.
I've added  django_extension to my requirements.txt fils and install it using this command:
pip install -r requirements.txt

**Comment by akudja238** [comment]
> 
> 
> @romulo-mesquita It was fixed for me by reinstalling django_extensions from the requirements.txt.
> I've added django_extension to my requirements.txt fils and install it using this command:
> pip install -r requirements.txt

please describe in more detail how

**Comment by dariocoroneldev** [comment]
i have the same issue, but even when i reinstall it in anyway dosen't work

**Comment by rainfidelis** [comment]
> 
> 
> i have the same issue, but even when i reinstall it in anyway dosen't work

Are you using pipenv? My own issue arose 'cos I installed with pip rather than pipenv. You might want to check that.

**Comment by OStewart-dev** [comment]
It should be 'django_extensions' and 'django-extensions'.
