### ISSUE TITLE
2.2.7 not work in django3.0.3, but 2.2.6 work ok

### ISSUE THREAD

**Issue by stfenjobs** [django-extensions/django-extensions#1478]
2.2.7 + django 3.0.3 + python 3.74 .    not work

2.2.7 + django 3.0.3 + python 3.81 .    not work

================================
2.2.6 + django 3.0.3 + python 3.81 .    **it's work**

error:
 ```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/contrib/auth/models.py", line 91, in <module>
    class Group(models.Model):
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/db/models/base.py", line 160, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1585, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1066, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/functional.py", line 160, in __mod__
    return str(self) % rhs
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/functional.py", line 124, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 92, in gettext
    return _trans.gettext(message)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 285, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 198, in translation
    _translations[language] = DjangoTranslation(language)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 97, in __init__
    self._add_installed_apps_translations()
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 145, in _add_installed_apps_translations
    translation = self._new_gnu_trans(localedir)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 119, in _new_gnu_trans
    return gettext_module.translation(
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/gettext.py", line 598, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/gettext.py", line 261, in __init__
    self._parse(fp)
  File "/Users/user01/opt/anaconda3/envs/pro2/lib/python3.8/gettext.py", line 456, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by stfenjobs** [comment]
my config:
```
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'
```

**Comment by trbs** [comment]
Please try with a different ’LANGUAGE_CODE‘ and see if that’s helps. 

It probably has something todo with the new translation file. 

If that helps we know the cause afterwards we can hopefully fix it or worse case remove the new translation file.

**Comment by maxmalysh** [comment]
Same problem for me. 

```
USE_I18N = True
USE_L10N = True
USE_TZ = True

TIME_ZONE = 'UTC'
TIME_ZONE_SESSION_KEY = '_timezone'
TIME_ZONES = [
    (tz, tz.replace('_', ' '))
    for tz in pytz.common_timezones
]


LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', 'English'),
    ('es', 'Español'),
    ('pt-br', 'Português'),  # "Português (Brasil)"
    ('ru', 'Русский'),
    ('zh-hans', '简体中文'),
)
```
```
django==3.0.3
django-extensions==2.2.7
```
2.2.6 works fine.

**Comment by zmrenwu** [comment]
I can confirm this. Maybe the new translation file missing the encoding declaration?

zh_Hans/django.po
```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy

#: admin/__init__.py:138
msgid "and"
msgstr "和"
```

![UnicodeDecodeError   ascii  codec can t decode byte 0xe6 in position 0  ordinal not in range 128 ](https://user-images.githubusercontent.com/13174219/74112161-a1a4a900-4bdd-11ea-90cc-7f2daf5b0272.png)

However, I make a demo django project only install 2.2.7 and set LANGUAGE_CODE = 'zh-hans', that works fine. But in large production project, I got UnicodeDecodeError.

**Comment by trbs** [comment]
See https://github.com/django-extensions/django-extensions/commit/cf0f84543b9ba4aa2a83b235d4e41ea82b0745d8 will do a new release shortly


    remove zh_Hans for now (see #1478)

    Currently gives UnicodeDecodeError error (see issue) in Python
    and read-mo.c:257: invalid multibyte sequence using msgunfmt

    Chosing to remove this for now until this can be fixed

**Comment by trbs** [comment]
https://pypi.org/project/django-extensions/2.2.8/
