### ISSUE TITLE
Pip 20.1 breaks pipchecker

### ISSUE THREAD

**Issue by Alexerson** [django-extensions/django-extensions#1521]
When upgrading to pip==20.1, the following exception appears:
```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "./lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "./lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "./lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "./lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "./lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "./lib/python3.8/site-packages/django_extensions/management/commands/pipchecker.py", line 92, in handle
    name = req.name if req.name else req.link.filename
AttributeError: 'ParsedRequirement' object has no attribute 'name'
```

It's working fine when downgrading to pip 20.0.1.

django-extensions==2.2.9

**Comment by Alexerson** [comment]
I tried to be helpful here but it appears the internals of pip changed quite a bit, so I won't be able to help much, except by saying the commit that changes everything is:
https://github.com/pypa/pip/commit/90e4eb3eedc7c550c2dd036b7a535cdec50a93d5#diff-851cc85103a872db421c81afadd4fee5

They changed the signature of the function and it now returns a different class. (see L176)

**Comment by yeojin-dev** [comment]
I modified this code before. Let me solve this problem. :)
