### ISSUE TITLE
error with dumpscript on a specific model

### ISSUE THREAD

**Issue by jeanwainer** [django-extensions/django-extensions#1584]
Hi,
So I'm trying to use dumpscript, but when I use it on a specific app (core), I have the error below when 
`(venv) jean@boodev:~/managym$ python manage.py dumpscript core > model_dumps/core.py
Processing model: core.models.Company
Processing model: core.models.CompanyOption
Processing model: core.models.Client
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 117, in handle
    self.stdout.write(str(script))
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 180, in __str__
    return flatten_blocks(self.lines, num_indents=self.indent)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 474, in get_lines
    code.append(model_class.lines)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 222, in get_lines
    code += instance.lines
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 287, in get_lines
    code_lines += self.get_waiting_list()
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 359, in get_waiting_list
    value = get_attribute_value(self.instance, field, self.context, force=force, skip_autofield=skip_autofield)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 696, in get_attribute_value
    item_locator = orm_item_locator(value)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django_extensions/management/commands/dumpscript.py", line 73, in orm_item_locator
    v = timezone.make_aware(v)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/django/utils/timezone.py", line 234, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/home/jean/managym/venv/lib/python3.8/site-packages/pytz/tzinfo.py", line 318, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
`

This appears to be something with my specific "Client" model. If it makes any difference, the model is below:
`class Client(models.Model):
    """
    Client information
    """
    company = models.ForeignKey(Company, blank=True, null=True, default=1, on_delete=models.SET_NULL)
    local_id = models.CharField(max_length=10, blank=True, null=True)
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True)
    photo = models.ImageField(blank=True, null=True, upload_to=picture_upload_path)
    cpf = models.CharField(max_length=20, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=GENDER_CHOICES[0][0], blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateField(default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    street = models.CharField(_("Street"), max_length=255, blank=True, null=True)
    street_number = models.CharField(_("Street Number"), max_length=55, blank=True, null=True)
    address2 = models.CharField(_("Address line 2"), max_length=255, blank=True, null=True)
    neighborhood = models.CharField(_("Neighborhood"), max_length=60, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=2, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, default='BRA', blank=True, null=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)`

Any ideas what could be causing this error?

**Comment by jaffcunha** [comment]
I have the same error and looking at our models i think it may be caused by
`models.DateTimeField(auto_now_add=True)`

**Comment by trbs** [comment]
Think we had these kind of issues (or similar) before... (If I remember correctly that had to do with how date/times where formatted as in the dumped script)

Sadly I cannot really work on this at the moment...
If anybody can detail the issue and make a PR for this that would be much appreciated. (or if you work for a company that can sponsor this work, please contact me directly)

**Comment by blueyed** [comment]
Related, but looks not like it would fix this issue, given that `make_aware` does not raise a `ValueError` here: https://github.com/django-extensions/django-extensions/pull/1745
