### ISSUE TITLE
Pipchecker network restrictions

### ISSUE THREAD

**Issue by SamuelMS** [django-extensions/django-extensions#1603]
I've been having issues running `pipchecker` for the last several months across multiple machines – I keep getting networking issues (`HTTPTooManyRequests`). Even our smaller projects with just a handful of dependencies run into this, and `pipchecker` ends up throwing an exception and exiting partway through.

Full stack trace follows:

```python
Traceback (most recent call last):
  File "/app/manage.py", line 30, in <module>
    main()
  File "/app/manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_extensions/management/commands/pipchecker.py", line 111, in handle
    self.check_pypi()
  File "/usr/local/lib/python3.9/site-packages/django_extensions/management/commands/pipchecker.py", line 148, in check_pypi
    available = pypi.package_releases(req["pip_req"].name, True) or pypi.package_releases(req["pip_req"].name.replace('-', '_'), True)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1456, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/local/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: 'HTTPTooManyRequests: The action could not be performed because there were too many requests by the client. Limit may reset in 1 seconds.'>
```

**Comment by trbs** [comment]
Could you try with the latest version on github ?

It should have some patches to help with this.
I am hoping to do a new release soon and it would really help if you could try the updated `pipchecker`.

`$ pip install -e git+https://github.com/django-extensions/django-extensions.git#egg=django-extensions`

**Comment by trbs** [comment]
Yeah that sounds about right (regretfully), think that's the state-of-the-world as-is right now.

With all the changes going into `pip` over the last year(s) I bet `pipchecker` could be updated to be a lot smart/better :-)
Loosing the need for the `xmlrpc` client would go a long way to fix this.

(If any company is using this and wishes to sponsor this work please contact me `trbs at trbs.net` or use one of the sponsor options)
