### ISSUE TITLE
`runserver_plus` returns `AttributeError: module 'django_extensions.management.commands.runserver_plus' has no attribute 'Command'`

### ISSUE THREAD

**Issue by shiriru** [django-extensions/django-extensions#1630]
With Python 3.9.1, django 2.2.18 and wagtail 2.7.1, when I try to run `django dev server` with:
```python
python manage.py runserver_plus
```
I am getting the following traceback:
```shell
Traceback (most recent call last):
  File "/home/vagrant/www/cms/project/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.pyenv/versions/py391dj22wt27/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.pyenv/versions/py391dj22wt27/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.pyenv/versions/py391dj22wt27/lib/python3.9/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/vagrant/.pyenv/versions/py391dj22wt27/lib/python3.9/site-packages/django/core/management/__init__.py", line 37, in load_command_class
    return module.Command()
AttributeError: module 'django_extensions.management.commands.runserver_plus' has no attribute 'Command'
```
This happened only after I updated `django-extensions` to the current latest version - 3.1.1
Never had an issue with `runserver_plus` in the same env before the update.

**Comment by trbs** [comment]
I cannot reproduce this:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ python3 -V
Python 3.9.1
$ pip install Django==2.2 Werkzeug
$ pip install -e .
$ django-admin start testproject
$ ./venv/bin/django-admin startproject testproject
$ vi testproject/testproject/settings.py
$ ./testproject/manage.py runserver_plus
You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.


Django version 2.2, using settings 'testproject.settings'
Development server is running at http://[127.0.0.1]:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: ***-***-***
```

Maybe something else is wrong ?
