### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unique'

### ISSUE THREAD

**Issue by caramdache** [django-extensions/django-extensions#1638]
I get the above error when trying to run `./manage.py sqldiff myapp`:

```
Traceback (most recent call last):
  File "/var/www/django/djpat/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/commands/sqldiff.py", line 1380, in run_from_argv
    super().run_from_argv(argv)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/commands/sqldiff.py", line 1367, in execute
    super().execute(*args, **options)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/commands/sqldiff.py", line 1360, in handle
    sqldiff_instance.find_differences()
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/commands/sqldiff.py", line 662, in find_differences
    self.find_index_missing_in_model(meta, table_indexes, table_constraints, table_name)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/django_extensions/management/commands/sqldiff.py", line 862, in find_index_missing_in_model
    if constraint['index'] and constraint['type'] == 'idx' and constraint.get('orders') and field.unique:
AttributeError: 'NoneType' object has no attribute 'unique'
```

**Comment by trbs** [comment]
Thanks for the report. Could you make a reproducible case / git / repo for this ?

To be honest I cannot promise I will get around to this any time soon, but without a way to test this the changes will be zero ;-)

(If you happen to work for a company that has a need for this work then PM me separately)
