### ISSUE TITLE
raise InvocationException( pydotplus.graphviz.InvocationException: GraphViz's executables not found

### ISSUE THREAD

**Issue by withrvr** [django-extensions/django-extensions#1641]
while running this command

`python manage.py graph_models -a -o myapp_models.png`

this error came to me how to solve this error ( issues )

Traceback (most recent call last):
  File "D:\MATERIAL\Raghav_Rathi\All_Coding_Files\Coding_Projects\1Link\OneLink\manage.py", line 22, in <module>
    main()
  File "D:\MATERIAL\Raghav_Rathi\All_Coding_Files\Coding_Projects\1Link\OneLink\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Python\python-39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python\python-39\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python\python-39\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python\python-39\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Python\python-39\lib\site-packages\django_extensions\management\utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "C:\Python\python-39\lib\site-packages\django_extensions\management\commands\graph_models.py", line 258, in handle
    return self.render_output_pydot(dotdata, **options)
  File "C:\Python\python-39\lib\site-packages\django_extensions\management\commands\graph_models.py", line 323, in render_output_pydot
    graph.write(output_file, format=format_)
  File "C:\Python\python-39\lib\site-packages\pydotplus\graphviz.py", line 1918, in write
    fobj.write(self.create(prog, format))
  File "C:\Python\python-39\lib\site-packages\pydotplus\graphviz.py", line 1959, in create
    raise InvocationException(
pydotplus.graphviz.InvocationException: GraphViz's executables not found

**Comment by trbs** [comment]
I am not a windows user but it sounds like you do not have GraphViz executables installed.

**Comment by withrvr** [comment]
> I am not a windows user but it sounds like you do not have GraphViz executables installed.

i have installed it
