### ISSUE TITLE
django 2.2 graph_models ImportError: cannot import name 'get_models'

### ISSUE THREAD

**Issue by muhammad-ammar** [django-extensions/django-extensions#1642]
I am trying to create database schema diagram for my django 2.2 project using commands mentioned onhttps://django-extensions.readthedocs.io/en/latest/graph_models.html#example-usage but all are failing due to below error

```
./manage.py graph_models -a -I Stocks -o my_project_subsystem.png
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/mammar/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django_extensions/management/commands/graph_models.py", line 8, in <module>
    from django_extensions.management.modelviz import generate_dot
  File "/Users/mammar/.pyenv/versions/om-subscription/lib/python3.6/site-packages/django_extensions/management/modelviz.py", line 15, in <module>
    from django.db.models import get_models
ImportError: cannot import name 'get_models'
```
I have tried `from django.db.models import get_models` and `get_models` is not present. Does that mean `django-extensions` is not compatible with `django 2.2`?

Please help to fix the issue.

**Comment by trbs** [comment]
We test against `Django 2.2` so we expect it to work. Anything not working against supported `Django` or `Python` versions for `Django Extensions` is considered a bug.

That said I cannot reproduce this:

```
$ pip freeze|grep -i Django==
Django==2.2
```

```
$ ./manage.py graph_models -a -o test.png
$ file test.png
test.png: PNG image data, 15551 x 1141, 8-bit/color RGB, non-interlaced
```

If this does persist for you please try to create a PR for a test case in our test suite that triggers this issue. That way we have something to help fix this and make sure it does not regresses later.
