### ISSUE TITLE
[sqldiff] IndexError: list index out of range

### ISSUE THREAD

**Issue by d3QUone** [django-extensions/django-extensions#1680]
ENV:
- Python 3.8.*
- Django 3.0.12
- django-extensions 2.2.9
- DB: Postgres 

Command 
```
python manage.py sqldiff -a
```

Error:
```python
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    main()
  File "manage.py", line 23, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/sqldiff.py", line 1298, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/sqldiff.py", line 1285, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/sqldiff.py", line 1278, in handle
    sqldiff_instance.find_differences()
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/sqldiff.py", line 663, in find_differences
    self.find_index_missing_in_model(meta, table_indexes, table_constraints, table_name)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/sqldiff.py", line 492, in find_index_missing_in_model
    field = fields.get(columns[0])
IndexError: list index out of range
make: *** [manage] Error 1
```

**Comment by TomD3Wiz** [comment]
Just bumped into this issue,  If it helps the constraint dictionary is defined as 

`{'columns': [], 'orders': ['ASC'], 'primary_key': False, 'unique': False, 'foreign_key': None, 'check': False, 'index': True, 'type': 'idx', 'definition': 'CREATE INDEX auth_user_username_upper ON public.auth_user USING btree (upper((username)::text))', 'options': None}`

**Comment by kevinmarsh** [comment]
Also just ran into this when trying out this command, for reference the constraint definition failing for me is something like
```sql
CREATE CONSTRAINT TRIGGER my_trigger
AFTER UPDATE
      OR INSERT
ON my_table
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION my_function();
```
And similar to the comment above, the constraint dictionary has `{'columns': [], ...}` so hopefully is a straightforward fix to prevent against empty columns introduced here: https://github.com/django-extensions/django-extensions/pull/1502/files#diff-62aa1b7afc057a55ca15d141a0bb9d7cdf090c7dedf229710c81dd8edc22dd28R492
