### ISSUE TITLE
KeyError: 'purelib'

### ISSUE THREAD

**Issue by atodorov** [django-extensions/django-extensions#1694]
Installing django-extensions in one of our CI workflows leads to the following issue:

```
Collecting django-extensions==3.1.5
  Downloading django-extensions-3.1.5.tar.gz (614 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/runner/work/Kiwi/Kiwi/.venv/test-tarball/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qrz6dexy/django-extensions_004cd98317984be880bd9c58355372c0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qrz6dexy/django-extensions_004cd98317984be880bd9c58355372c0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_c6s15hw
       cwd: /tmp/pip-install-qrz6dexy/django-extensions_004cd98317984be880bd9c58355372c0/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-qrz6dexy/django-extensions_004cd98317984be880bd9c58355372c0/setup.py", line 53, in <module>
      scheme['data'] = scheme['purelib']
  KeyError: 'purelib'
```

Full logs at https://github.com/kiwitcms/Kiwi/runs/4595761041?check_suite_focus=true

while on my devel machine I see that I've installed django-extensions successfully. 

Both are python 3.8 but different versions and OS. 

Any hints or workarounds ?

**Comment by atodorov** [comment]
Here's another log from CI which passed with the same version of django-extensions: https://github.com/kiwitcms/Kiwi/runs/4550032959?check_suite_focus=true This is 5 days ago.
