### ISSUE TITLE
requires_system_checks must be a list or tuple.

### ISSUE THREAD

**Issue by isantolin** [django-extensions/django-extensions#1750]
**- Django Version:** 4.1rc1
**- Django Extensions Version:** 3.2.0
**- Python Version:** 3.9.9

I tried to use Django Extensions in Django 4.1rc1 but using runserver_plus, shows me that error when i try to Run my Django Project. Removing Django Extensions, Works

/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/bin/python /home/xxxx/PycharmProjects/DJ_Basic-RegLogin/manage.py runserver_plus --cert-file localhost.crt
Traceback (most recent call last):
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/manage.py", line 21, in <module>
    main()
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 49, in load_command_class
    return module.Command()
  File "/home/xxxx/PycharmProjects/DJ_Basic-RegLogin/venv/lib/python3.9/site-packages/django/core/management/base.py", line 274, in __init__
    raise TypeError("requires_system_checks must be a list or tuple.")
TypeError: requires_system_checks must be a list or tuple.

Process finished with exit code 1

**Comment by spapanik** [comment]
It happens with the released version of django 4.1 as well.

**Comment by SFr682k** [comment]
There is already a pull request implementing the required changes: #1736

**Comment by devmonkey22** [comment]
Can we close this ticket as it was merged via https://github.com/django-extensions/django-extensions/pull/1736 back in version 3.2.x I believe?
