### ISSUE TITLE
runserver_plus raise TypeError: requires_system_checks must be a list or tuple.

### ISSUE THREAD

**Issue by hirakhax** [django-extensions/django-extensions#1755]
`Traceback (most recent call last):
  File "/home/hirakhax/Desktop/Programs/textbookwiki/manage.py", line 22, in <module>
    main()
  File "/home/hirakhax/Desktop/Programs/textbookwiki/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/hirakhax/Desktop/Programs/textbookwiki/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/hirakhax/Desktop/Programs/textbookwiki/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hirakhax/Desktop/Programs/textbookwiki/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/hirakhax/Desktop/Programs/textbookwiki/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 49, in load_command_class
    return module.Command()
  File "/home/hirakhax/Desktop/Programs/textbookwiki/venv/lib/python3.10/site-packages/django/core/management/base.py", line 274, in __init__
    raise TypeError("requires_system_checks must be a list or tuple.")
TypeError: requires_system_checks must be a list or tuple.`

**Comment by hirakhax** [comment]
requirements.txt
===============
Django>=4.1.0,<4.1.1
Pillow
Faker
django-tailwind
django-quill-editor>=0.1.40,<0.2.0
social-auth-app-django==5.0.0

# For Development
django-extensions==3.0.9
werkzeug==2.2.2
pyOpenSSL==22.0.0

**Comment by ulgens** [comment]
@hirakhax https://github.com/django-extensions/django-extensions/pull/1736
