### ISSUE TITLE
can't start runserver_plus  TypeError: requires_system_checks must be a list or tuple.

### ISSUE THREAD

**Issue by alirezaimi** [django-extensions/django-extensions#1756]
Hi 
I want to use runserver_plus and get this error : 

        $ python3 manage.py runserver_plus
    Traceback (most recent call last):
      File "/mydjangosite/imiteldjango/manage.py", line 22, in <module>
        main()
      File "/mydjangosite/imiteldjango/manage.py", line 18, in main
        execute_from_command_line(sys.argv)
      File "/mydjangosite/imiteldjango/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
        utility.execute()
      File "/mydjangosite/imiteldjango/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/mydjangosite/imiteldjango/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 279, in fetch_command
        klass = load_command_class(app_name, subcommand)
      File "/mydjangosite/imiteldjango/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 49, in load_command_class
        return module.Command()
      File "/mydjangosite/imiteldjango/venv/lib/python3.10/site-packages/django/core/management/base.py", line 274, in __init__
        raise TypeError("requires_system_checks must be a list or tuple.")
    TypeError: requires_system_checks must be a list or tuple.

    $ pip3 install django-extensions Werkzeug django 
    Requirement already satisfied: django-extensions in ./venv/lib/python3.10/site-packages (3.2.0)
    Requirement already satisfied: Werkzeug in ./venv/lib/python3.10/site-packages (2.2.2)
    Requirement already satisfied: django in ./venv/lib/python3.10/site-packages (4.1)
    Requirement already satisfied: MarkupSafe>=2.1.1 in ./venv/lib/python3.10/site-packages (from Werkzeug) (2.1.1)
    Requirement already satisfied: asgiref<4,>=3.5.2 in ./venv/lib/python3.10/site-packages (from django) (3.5.2)
    Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.10/site-packages (from django) (0.4.2)

**Comment by ulgens** [comment]
https://github.com/django-extensions/django-extensions/pull/1736

**Comment by Ezrahel** [comment]
I'm also having the same error each time I run python manage.py runserver_plus --cert-file cert.crt

**Comment by LinnaViljami** [comment]
same problem

**Comment by trbs** [comment]
I'll try to make a new release soon :-)
