### ISSUE TITLE
TypeError: run_simple() got an unexpected keyword argument 'exclude_patterns' with django-extensions 3.2.1

### ISSUE THREAD

**Issue by simevo** [django-extensions/django-extensions#1767]
trace:
```
django          | TypeError: run_simple() got an unexpected keyword argument 'exclude_patterns'
django exited with code 1
django          | Traceback (most recent call last):
django          |   File "/app/manage.py", line 16, in <module>
django          |     execute_from_command_line(sys.argv)
django          |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
django          |     utility.execute()
django          |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 440, in execute
django          |     self.fetch_command(subcommand).run_from_argv(self.argv)
django          |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 414, in run_from_argv
django          |     self.execute(*args, **cmd_options)
django          |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 460, in execute
django          |     output = self.handle(*args, **options)
django          |   File "/usr/local/lib/python3.9/dist-packages/django_extensions/management/utils.py", line 62, in inner
django          |     ret = func(self, *args, **kwargs)
django          |   File "/usr/local/lib/python3.9/dist-packages/django_extensions/management/commands/runserver_plus.py", line 296, in handle
django          |     self.inner_run(options)
django          |   File "/usr/local/lib/python3.9/dist-packages/django_extensions/management/commands/runserver_plus.py", line 414, in inner_run
django          |     run_simple(
django          | TypeError: run_simple() got an unexpected keyword argument 'exclude_patterns'
```
does not happen with django-extensions==3.2.0

`pip freeze` reports:
```
amqp==5.1.1
appdirs==1.4.4
argon2-cffi==18.3.0
asgiref==3.5.2
astroid==2.5.1
attrs==20.3.0
backcall==0.2.0
billiard==3.6.4.0
black==20.8b1
celery==5.2.3
certifi==2020.6.20
cfgv==3.2.0
chardet==4.0.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.4
coverage==5.1
cryptography==3.3.2
decorator==4.4.2
defusedxml==0.7.1
distlib==0.3.1
Django==4.0.7
django-appconf==1.0.5
django-auth-ldap==4.1.0
django-celery-beat==2.3.0
django-coverage-plugin==2.0.3
django-crispy-forms==1.14.0
django-cryptography==1.1
django-debug-toolbar==3.6.0
django-environ==0.9.0
django-extensions==3.2.1
django-mass-edit==3.4.1
django-model-utils==4.2.0
django-stubs==1.12.0
django-stubs-ext==0.5.0
django-timezone-field==5.0
django-wkhtmltopdf==3.4.0
djangorestframework==3.13.1
djangorestframework-simplejwt==5.2.0
djangorestframework-xml==2.0.0
factory-boy==2.11.1
Faker==0.9.3
filelock==3.0.12
flake8==3.8.4
flake8-isort==4.2.0
flower==1.2.0
hiredis==1.0.1
humanize==4.3.0
identify==1.5.13
idna==2.10
importlib-metadata==1.6.0
iniconfig==0.0.0
ipdb==0.13.3
ipython==7.20.0
ipython-genutils==0.2.0
isort==5.6.4
jedi==0.18.0
kombu==5.2.4
lazy-object-proxy==0.0.0
logilab-common==1.8.1
mccabe==0.6.1
more-itertools==4.2.0
mypy==0.971
mypy-extensions==0.4.3
needle @ git+https://github.com/timdiels/needle.git@4393f11431dfa8c946e9db34ffe311fcffa46eb6
nodeenv==0.13.4
nose==1.3.7
packaging==20.9
parso==0.8.1
pathspec==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.2
pluggy==0.13.0
pre-commit==2.10.1
prometheus-client==0.14.1
prompt-toolkit==3.0.31
psutil==5.8.0
psycopg2==2.8.6
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycodestyle==2.6.0
pyflakes==2.2.0
Pygments==2.7.1
PyJWT==2.1.0
pylint==2.7.2
pylint-django==2.0.13
pylint-plugin-utils==0.6
pyparsing==2.4.7
pytest==6.0.2
pytest-django==3.5.1
pytest-sugar==0.9.4
python-crontab==2.6.0
python-dateutil==2.8.1
python-ldap==3.2.0
python-slugify==4.0.0
pytz==2022.1
PyYAML==5.3.1
rcssmin==1.0.6
redis==3.5.3
regex==2020.11.13
requests==2.25.1
selenium==3.141.0
six==1.16.0
sqlparse==0.4.2
termcolor==1.1.0
toml==0.10.1
tomli==2.0.1
tornado==6.2
traitlets==5.0.5
typed-ast==1.4.2
types-pytz==2022.2.1.0
types-PyYAML==6.0.11
typing-extensions==4.3.0
tzdata==2022.2
Unidecode==1.2.0
urllib3==1.26.5
vine==5.0.0
virtualenv==20.4.0+ds
wcwidth==0.2.5
Werkzeug==1.0.1
whitenoise==5.2.0
wrapt==1.12.1
zipp==1.0.0
```

**Comment by trbs** [comment]
Sorry that's a bit of an annoying regression... 

With https://github.com/django-extensions/django-extensions/issues/1753 we now require Werkzeug>=2.0.0

2.0.0 was released 2021-05-11, so it's not _that_ old :-)

I would like to support earlier versions if we can.
Happy to accept a PR for that if the solution is relatively clean.

**Comment by simevo** [comment]
HI, and many thanks for the superfast answer.

I have realized that on the system where this occurred we had installed werkzeug using the operating system package manager, and [since we're on Debian stable we got werkzeug 1](https://packages.debian.org/bullseye/python3-werkzeug). We have no problem updating that dependency!

To avoid similar trouble to other people the django-extensions Python package should advertise that it requires `Werkzeug>=2.0.0` so that the incompatibility is detected at install time (`pip install django-extensions`).

**Comment by truthdoug** [comment]
Expanding on @trbs's comment above, it was specifically "Improvement: runserver_plus, Add option to ignore files on runserver_plus reload" (#1762), released in version 3.2.1 that introduced this change.
