### ISSUE TITLE
Error when attempting to use reset_db on remote managed database

### ISSUE THREAD

**Issue by edmundsj** [django-extensions/django-extensions#1799]
Ok, so I have setup a managed database with Digital Ocean, and I am trying to use `django-extensions` to reset that database by running `reset_db`. Simple enough. I can connect to the database via `psql`, and django can communicate with the database perfectly. However, when and ONLY when I run `reset_db`, I get an error saying I cannot connect to the database. I have plopped the traceback below. My suspicion is that `reset_db` doesn't support `SSL`, but this seems weird to me.

It also seems strange that I specify database `defaultdb` explicitly, and the traceback says it's attempting to connect to database `template1`. This seems like a bug, or a misunderstanding of what's going on under the hood on my part.

```
root@ddaed4b159a5:/app# python3 manage.py reset_db -D defaultdb

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "defaultdb".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django_extensions/management/commands/reset_db.py", line 156, in handle
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***" (***), port 25060 failed: FATAL:  pg_hba.conf rejects connection for host "***", user "doadmin", database "template1", SSL encryption
connection to server at "***" (***), port 25060 failed: FATAL:  no pg_hba.conf entry for host "***", user "doadmin", database "template1", no encryption

usage: manage.py reset_db [-h] [--noinput] [--no-utf8] [-U USER] [-O OWNER] [-P PASSWORD] [-D DBNAME]
                          [-R ROUTER] [--database DATABASE] [-c] [--version] [-v {0,1,2,3}]
                          [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                          [--force-color] [--skip-checks]
```

**Comment by edmundsj** [comment]
I think I found the offending "fix" [here](https://github.com/django-extensions/django-extensions/commit/04f52d5b89e4f1d95e73de3cc5435ba7593ba233) that causes this problem. Unfortunately, digital ocean does not allow access to the `template0` or `template1` databases, and it is not possible to create `template0` or `template1` databases which *can* be connected to, which means this will have to be changed to work with digitalocean databases (and I suspect other cloud providers as well which restrict connection to these template databases). I can create additional databases with other names. Here is my suggested fix:

Add a flag `--fallback DATABASE` which replaces `template1` if it is specified.
