### ISSUE TITLE
`drop_test_database` not compatible with psycopg3

### ISSUE THREAD

**Issue by danjac** [django-extensions/django-extensions#1811]
It appears that the `drop_test_database` command is hardcoded for psycopg2 and will break with psycopg3 (supported on Django 4.2+):

Python: 3.11
Django: 4.2
Postgres: 15.0
psycopg[binary]: 3.18

```bash
You have requested to drop all test databases.
This will IRREVERSIBLY DESTROY
ALL data in the database "test_postgres"
and all cloned test databases generated via
the "--parallel" flag (these are sequentially
named "test_postgres_1", "test_postgres_2", etc.).
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "./manage.py", line 26, in <module>
    main()
  File "./manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "my-path/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/my-path/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/my-path/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/my-path/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-path/lib/python3.11/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-path/lib/python3.11/site-packages/django_extensions/management/commands/drop_test_database.py", line 170, in handle
    import psycopg2 as Database  # NOQA
```

**Comment by adi-** [comment]
Same with `reset_db.py`

**Comment by jensenbox** [comment]
Is there a workaround at all?

```text

Traceback (most recent call last):
  File "/app/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_extensions/management/commands/reset_db.py", line 144, in handle
    import psycopg2 as Database  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'psycopg2'
```
