### ISSUE TITLE
`ReferenceError` when using `list_signals`

### ISSUE THREAD

**Issue by jvacek** [django-extensions/django-extensions#1851]
This is from Django 4.2:
```
Traceback (most recent call last):
  File "/Users/jvacek/repositories/my_repo/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django_extensions/management/commands/list_signals.py", line 41, in handle
    signals = [obj for obj in gc.get_objects() if isinstance(obj, ModelSignal)]
  File "/Users/jvacek/.pyenv/versions/3.10.3/envs/my_repo/lib/python3.10/site-packages/django_extensions/management/commands/list_signals.py", line 41, in <listcomp>
    signals = [obj for obj in gc.get_objects() if isinstance(obj, ModelSignal)]
ReferenceError: weakly-referenced object no longer exists
```

**Comment by foarsitter** [comment]
Dumping a trace like is of no help @jvacek, so can you please provide some more context?
