### ISSUE TITLE
AttributeError when running ./manage graph_models

### ISSUE THREAD

**Issue by ellochkaCannibal** [django-extensions/django-extensions#294]
When running ./manage graph_models on my app i get the following error:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django_extensions/management/commands/graph_models.py", line 41, in handle
    dotdata = generate_dot(args, **options)
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django_extensions/management/modelviz.py", line 217, in generate_dot
    add_relation(field, '[arrowhead=none, arrowtail=dot]')
  File "/home/ellochka/.virtualenvs/kit/local/lib/python2.7/site-packages/django_extensions/management/modelviz.py", line 196, in add_relation
    'target_app': target_model.__module__.replace('.', '_'),
AttributeError: 'str' object has no attribute '__module__'

**Comment by chrismeyersfsu** [comment]
I'm experiencing this error also.

**Comment by trbs** [comment]
So it's still an issue :(

Please provide a test case for this.
