### ISSUE TITLE
ImportError: cannot import name 'force_unicode'

### ISSUE THREAD

**Issue by LeMeteore** [django-extensions/django-extensions#609]
I tried to use the describe_form command and this is the output I had:

```
> python manage.py describe_form photo.photo
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nsukami/envs/wappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/nsukami/envs/wappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nsukami/envs/wappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/nsukami/envs/wappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/nsukami/envs/wappa/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nsukami/envs/wappa/lib/python3.4/site-packages/django_extensions/management/commands/describe_form.py", line 2, in <module>
    from django.utils.encoding import force_unicode
ImportError: cannot import name 'force_unicode'
```

I'm currently using python 3.4.2, django 1.7.4, and django-extensions 1.4.9. And the error was (I hope) fixed replacing all the occurences of `force_unicode` by `force_text` inside `/home/nsukami/envs/wappa/lib/python3.4/site-packages/django_extensions/management/commands/describe_form.py` file. 

Is there something I'm missing or doing wrong? Thx.

**Comment by trbs** [comment]
No, this is a bug :)

I have fixed this in git, there will be a new release soon.
Thanks for reporting this!

**Comment by LeMeteore** [comment]
It's nothing. Thanks to you for the quick reply.
