### ISSUE TITLE
pipchecker doesn't works with latest pip version

### ISSUE THREAD

**Issue by dvl** [django-extensions/django-extensions#630]
Since I've updated pip to latest version I can't use pipchecker anymore, if I downgrade pip to previous version it works fine.

```
$ ./manage.py pipchecker
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django_extensions/management/utils.py", line 77, in inner
    ret = func(self, *args, **kwargs)
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/django_extensions/management/commands/pipchecker.py", line 72, in handle_noargs
    for req in parse_requirements(filename, options=mockoptions):
  File "/home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

```
$ pip --version
pip 6.0.8 from /home/dvl/.virtualenvs/infobusca/lib/python3.4/site-packages (python 3.4)
```

**Comment by trbs** [comment]
Thanks for reporting this !

This fix also works for me on 1.5.6 up to 6.0.8.
Could you please test it ?

It also leaves room for further improvements by allowing to support pip command line options like ```--cache-dir``` and ```--cert``` etc.

**Comment by dvl** [comment]
The command is working now, but it's failing to find some packages.

Example:

    # requirements.txt
    Django==1.7.4  # the package name is capitalized on pypi
    model_mommy==1.2.3  # the package name has underscore on pypi

with pip 6.0.8 I got the following output:

    $ m pipchecker        
    Django 1.7.4                     release is not on pypi (check capitalization and/or --extra-index-url)
    model-mommy 1.2.3                release is not on pypi (check capitalization and/or --extra-index-url)

and with pip 1.5.6:

    $ m pipchecker
    Django 1.7.4                     1.8b1 available


Thanks for your help

**Comment by kevgathuku** [comment]
@dvl @trbs I've submitted a patch that for now fixes the issue with packages starting with an uppercase letter not being parsed correctly. 
Would really love to hear your feedback on it.

**Comment by kevgathuku** [comment]
Here's the output I'm getting
```
(generator)kevin@kingkev-pc ~/code/projects/redditclone $ ./manage.py pipchecker
django-toolbelt                          not installed
Pillow 2.7.0                     2.8.1 available
Django 1.7.4                     1.8 available
prospector 0.9.9                 0.10 available
```
