### ISSUE TITLE
1.5.1 sqldiff: KeyError exception when index does not exists

### ISSUE THREAD

**Issue by kurevin** [django-extensions/django-extensions#639]
```
python manage.py sqldiff -ad

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 999, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 983, in execute
    super(Command, self).execute(*args, **options)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 976, in handle
    sqldiff_instance.find_differences()
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 505, in find_differences
    self.find_unique_missing_in_db(meta, table_indexes, table_constraints, table_name)
  File "/mnt/data/work/Python-Backends/.venv/local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 311, in find_unique_missing_in_db
    db_field_unique = table_indexes[attname]['unique']
KeyError: 'uuid'
```

**Comment by trbs** [comment]
Would it be possible to provide a reproducible case for this ? (eg: a gist or github repo that has this issue)

**Comment by kurevin** [comment]
Create a model with unique=True on  some fields, sync it, manually remove all constraints and indexes from DB.
Use PostgreSQL.

**Comment by kurevin** [comment]
Also, while there. 
```python
db_field_unique = any(constraint['unique'] for contraint_name, constraint in six.iteritems(table_constraints) if attname in constraint['columns'])
```
Is not exactly correct, since db can have uniq together constraint that on columns [a, b], but missing uniq constraint on single column b, sqldiff will report that everything is fine while DB is really missing uniq constraint.
The better check is 
```[attname] == constraint['columns']```

**Comment by trbs** [comment]
Thanks ! changes are applied to the git version.
