### ISSUE TITLE
pipchecker not working with pip version 6.1.1 

### ISSUE THREAD

**Issue by kevgathuku** [django-extensions/django-extensions#659]
When I run `manage.py pipchecker` with pip 6.1.1 version installed, I am getting the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django_extensions/management/utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/django_extensions/management/commands/pipchecker.py", line 77, in handle_noargs
    "url": req.url,
  File "/home/kevin/.virtualenvs/gentest/lib/python2.7/site-packages/pip/req/req_install.py", line 128, in url
    return self.link.url
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by kevgathuku** [comment]
Resolved in #662
