### ISSUE TITLE
Django 1.9 Exception: module removed

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#707]
Traceback due to `django.db.models.loading` being removed (https://docs.djangoproject.com/en/dev/releases/1.9/#features-removed-in-1-9):

```
Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 331, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 323, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/base.py", line 350, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/base.py", line 401, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/base.py", line 590, in handle
    return self.handle_noargs(**options)
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/site-packages/django_extensions/management/utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/site-packages/django_extensions/management/commands/shell_plus.py", line 312, in handle_noargs
    shell = func()
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/site-packages/django_extensions/management/commands/shell_plus.py", line 178, in get_plain
    imported_objects = import_objects(options, self.style)
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/site-packages/django_extensions/management/shells.py", line 99, in import_objects
    from django.db.models.loading import get_models, get_apps
ImportError: No module named 'django.db.models.loading'
```

**Comment by jaddison** [comment]
I'm not sure what changed between `v1.5.5` and current `master`, but `shell_plus` now works. Closing as fixed.

**Comment by trbs** [comment]
Yeah some fixes for Django 1.9 went in :) Expect a new release soon.

**Comment by grumpa** [comment]
I have this issue here and now. pyvenv-3.4, django-1.9.

ImportError: No module named 'django.db.models.loading'

**Comment by trbs** [comment]
Not enough information... please people remember we are not payed for this nor do we have the time to start figuring out from one or two lines what the actual problem is.

Either donate towards the project and/or please provide fully reproducible test cases.

**Comment by grumpa** [comment]
I'm sorry. The command was "describe_form". I hope it's more helpful.

**Comment by natsn** [comment]
@trbs @grumpa I get the same error.

`python manage.py describe_form vibi.ContactLog`

got

`ImportError: No module named 'django.db.models.loading'`

**Comment by trbs** [comment]
committed fix in github for this issue.

**Comment by natsn** [comment]
Thanks

**Comment by trbs** [comment]
FYI: 1.6.7 has been released with this fix

**Comment by pyskell** [comment]
Getting the same error with 1.10.1
