### ISSUE TITLE
Django 1.9 Exception: can't adapt Type JSONDict

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#708]
**Edit: confirmed that this is still an issue in the `master` branch as of today.**

I realize Django 1.9 isn't out yet - but in working with it, I've discovered that recent changes  in django cause the following traceback relating django-extensions. I use `JSONField()` on one of my models and try to `get_or_create` that model, passing in no data for the json field.

Perhaps related to `psycopg2`'s http://initd.org/psycopg/docs/faq.html#problems-with-type-conversions type adapting requirements? 

```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 463, in get_or_create
    return self.get(**lookup), False
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
users.models.social.DoesNotExist: SocialConnection matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: can't adapt type 'JSONDict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 331, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 323, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/base.py", line 350, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/base.py", line 401, in execute
    output = self.handle(*args, **options)
  File "/vagrant/utils/management/commands/migrate_proj.py", line 140, in handle
    self.migrate_users(conn)
  File "/vagrant/utils/management/commands/migrate_proj.py", line 123, in migrate_users
    token=facebook_token
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 465, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 497, in _create_object_from_params
    obj = self.create(**params)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/base.py", line 674, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/base.py", line 702, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/base.py", line 786, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/base.py", line 825, in _do_insert
    using=using, raw=raw)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/query.py", line 1033, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: can't adapt type 'JSONDict'
```

**Comment by trbs** [comment]
No problem, please keep submitting the Django 1.9 issues, really appreciate it !
I might not be able to get to them right away but they all need to be fixed before 1.9 comes out.

**Comment by lamby** [comment]
For some reason we are calling to_python, so we dumps to a string and then Django calls to_python and turns it back into a JSONDict.. which then fails to save. 

This seems to "work" but it smells funny. https://gist.github.com/0dfb95201937d1a19ea3

**Comment by trbs** [comment]
Worsed case we could probably drop this field from ```django-extensions```.
I would recommend everybody to use the native (to both Django and PostgreSQL) json field: https://github.com/django/django/blob/master/django/contrib/postgres/fields/jsonb.py

**Comment by lamby** [comment]
Oh nice, didn't see that landed in django.git...

**Comment by jaddison** [comment]
In django 1.9, it is a postgresql only field. Also, it requires postgresql 9.4.

https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField

**Comment by jaddison** [comment]
Any thoughts on this, now that Django 1.9 is released? I'm not sure that dropping the field is a good idea, since many people won't be on PostgreSQL 9.4 and even if so, I'm not sure that one can cleanly switch out django-extensions JSONField for Django 1.9's without any effort. There would have to be an upgrade path for them to follow?

Surely there can be an immediate fix for this, but deprecate the field over time if there is a desire to push people to use Django's built-in JSONField? (even though non-PostgreSQL devs won't have any option)

**Comment by jaddison** [comment]
Wondering if maybe this Django 1.9 change had something to do with it: https://github.com/django/django/commit/19e67c6cd13d6442abb2a6eba1b7fba80dcf5457

**Comment by trbs** [comment]
Should be fixed with #772 if not please reopen.

**Comment by richarddewit** [comment]
Is this patch released? I get the same error after upgrading to Django 1.9

**Comment by richarddewit** [comment]
Sorry, I see it's been reverted. When I use 1.6.0 with Django 1.9 it works just fine.

**Comment by trbs** [comment]
Regretfully the patch in 1.6.0 caused serious problems for some people so it had to be reverted :(

**Comment by tuttle** [comment]
Once upgraded Django to 1.9 and django-extensions to 1.6.1 there's error "can't adapt Type JSONDict" on `get_or_create`. Using Postgresql < 9.4. What's the recommentation of the least effort, please? Thank you.

**Comment by tuttle** [comment]
@trbs Sorry for bugging you via this closed ticked, but I don't think the latest release 1.6.1 fixed this. Please take a look at my previous comment here. Thank you very much.
