### ISSUE TITLE
graph_models fails in Python 3.x

### ISSUE THREAD

**Issue by JoseTomasTocino** [django-extensions/django-extensions#740]
Looks like trying to graph the built-in `django.contrib.auth` models in a fresh install with Python 3.x fails due to string-handling issues. **Testcase**:

```
mkdir testcase
pyvenv-3.4 myenv
source myenv/bin/activate
pip install django django_extensions pygraphviz
django-admin startproject testproject .
```

Then add `django_extensions` to `INSTALLED_APPS` and run:

```
./manage.py graph_models -g -o myapp_models.png -R -S -n -a
```

This appears:

``` text.python.traceback
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django_extensions/management/utils.py", line 57, in inner
    ret = func(self, *args, **kwargs)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django_extensions/management/commands/graph_models.py", line 77, in handle
    dotdata = generate_dot(args, cli_options=cli_options, **options)
  File "/home/jose/test333/myenv/lib/python3.4/site-packages/django_extensions/management/modelviz.py", line 141, in generate_dot
    model['label'] = appmodel._meta.verbose_name.decode("utf8")
AttributeError: '__proxy__' object has no attribute 'decode'
```

**Comment by trbs** [comment]
Hope this is solved with the above PR's :)
