### ISSUE TITLE
empty south migration causes exception latest Django stable/1.9.x branch

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#757]
Perhaps something to do with this ticket (although I'm unsure): https://code.djangoproject.com/ticket/25627, I get this traceback:

```

/vagrant$ ./manage.py runserver
/home/vagrant/.virtualenvs/myproject/src/django/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)

/home/vagrant/.virtualenvs/myproject/src/django/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)

Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f505ae8d510>
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/home/vagrant/.virtualenvs/myproject/src/django/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/home/vagrant/.virtualenvs/myproject/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/.virtualenvs/myproject/lib/python3.4/site-packages/django_extensions/migrations/0001_empty.py", line 2, in <module>
    from south.v2 import SchemaMigration
ImportError: No module named 'south'
```

This was the commit that is causing the issue, I believe: https://github.com/django/django/commit/c4af8eb366be45420e13a400cc1dcc8fab91c1ad

**Comment by claudep** [comment]
https://docs.djangoproject.com/en/1.8/topics/migrations/#libraries-third-party-apps

**Comment by jaddison** [comment]
From #django-dev:

```
[10:12:13]  <+claudep>	jaddison: clearly, django_extensions should rename the migrations folder to south_migrations
[10:12:14]  <+carljm>	jaddison: You can add a MIGRATION_MODULES setting of {'django_extensions': None} -- that'll prevent Django from trying to load those migrations.
```
