### ISSUE TITLE
django 1.8.6 south error

### ISSUE THREAD

**Issue by MounirMesselmeni** [django-extensions/django-extensions#761]
After updating to django 1.8.6, also updating django-extensions to 1.5.8 I got this error

```python
Unhandled exception in thread started by <function wrapper at 0x7f67986182a8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 168, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

**Comment by dhilipsiva** [comment]
Same with my Migrations
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/core/management/commands/makemigrations.py", line 63, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/Users/dhilipsiva/ENV/appknox/sherlock/lib/python3.5/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

**Comment by skorokithakis** [comment]
Fixed in #760.

**Comment by skorokithakis** [comment]
Actually, I'm still getting this with 1.5.8, even though there's no `migrations` directory in the tgz.

**Comment by skorokithakis** [comment]
Ah, but there is one in the wheel.

**Comment by trbs** [comment]
In your local wheel (cache) ? or the official wheel ?

Cause I'm looking at ```django_extensions-1.5.8-py2.py3-none-any.whl``` and I don't see any migrations directory in that one...

**Comment by trbs** [comment]
fix is on the way

**Comment by trbs** [comment]
sorry about that, 1.5.9 was released to fix this

**Comment by dhilipsiva** [comment]
I can confirm that this is fixed now. Just ran it locally on my machine. This can be closed now. Thanks a lot Guys.

**Comment by trbs** [comment]
Thanks !

**Comment by MounirMesselmeni** [comment]
Fixed, thanks a lot !

**Comment by tobiasgoecke** [comment]
Thanks!
