### ISSUE TITLE
Migrated app 'django_extensions' contains South migrations

### ISSUE THREAD

**Issue by levchik** [django-extensions/django-extensions#763]
I've got clean Django 1.8.6 setup with django-extensions 1.5.7. South is not installed.

On ./manage.py migrate, it gives me the following:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/Users/lev/.virtualenvs/questplay/lib/python3.4/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

I don't remember having this problem with Django 1.8.5.
Is there any reason for django to look for South migrations instead of new style ones?

**Comment by trbs** [comment]
For more information about this please read: https://code.djangoproject.com/ticket/25618
This problem should be fixed in version 1.5.9 of django-extensions.

If there any issues left with 1.5.9 and Django 1.8.6 please don't hesitate to open another issue.
