### ISSUE TITLE
invalid connection option "fallback_application_name"

### ISSUE THREAD

**Issue by eliasj** [django-extensions/django-extensions#768]
Since 1.5.6 I get the error blow when I try to write to PostgreSQL. I think it's was introduced by #714 and because I use a older version of PostgreSQL fallback_application_name is not supported. It seems that it was introduced in 9.0.

```
>>> n.save()
Traceback (most recent call last):
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: invalid connection option "fallback_application_name"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/models/base.py", line 759, in save_base
    with transaction.atomic(using=using, savepoint=False):
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ejohael/Proj/web/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ej/Proj/web/venv/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: invalid connection option "fallback_application_name"

>>> 
[venv] selndev01:~/Proj/web> postgres --version
postgres (PostgreSQL) 8.4.13
[venv] selndev01:~/Proj/web> cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.4 (Santiago)
```

**Comment by trbs** [comment]
Officially PostgreSQL 8.x is not support anymore by Django.
But I'm more then happy to exact patches for this.

**Comment by robertolopezlopez** [comment]
I can replicate this same error with django-extensions 1.6.1 and postgresql 9.3.11. Using manage.py shell (not shell_plus) avoids the error, and I can see that fallback_application_name is defined in shell_plus.py:318.

> (venv_2.7.5)-bash-4.1$ pip freeze
Babel==2.2.0
Django==1.9.2
Fabric==1.10.2
Pygments==2.1
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.22
bpython==0.13.2
celery==3.1.20
django-appconf==1.0.1
django-braces==1.8.1
django-celery==3.1.17
django-classy-tags==0.7.1
django-compressor==2.0
django-cookie-law==1.0.6
django-extensions==1.6.1
django-fabric==2.1.0
django-jquery==1.9.1
django-phonenumber-field==1.0.0
ecdsa==0.13
kombu==3.0.33
paramiko==1.16.0
phonenumbers==7.2.4
psycopg2==2.6.1
pycrypto==2.6.1
python-magic==0.4.10
pytz==2015.7
rcssmin==1.0.6
redis==2.10.5
requests==2.9.1
rjsmin==1.0.12
six==1.10.0
wsgiref==0.1.2
(venv_2.7.5)-bash-4.1$ ack fallback_application_name
venv_2.7.5/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py
312:            Use the fallback_application_name to let the user override
318:            opt_name = 'fallback_application_name'

**Comment by trbs** [comment]
Are you sure you compiled psycopg2 with libpq-dev from PG 9.0 or higher ?

fallback_application_name is listed here http://www.postgresql.org/docs/9.3/static/libpq-connect.html

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
