### ISSUE TITLE
Apparent Cyclic import with in django when starting shell_plus --notebook

### ISSUE THREAD

**Issue by nanorepublica** [django-extensions/django-extensions#771]
Hi there,

I am getting the following whenever I try to use `shell_plus --notebook` all is well when I just use `shell_plus`

```python-traceback
[IPKernelApp] WARNING | Error in loading extension: django_extensions.management.notebook_extension
Check your config files in /home/vagrant/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/shellapp.py", line 267, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 91, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 138, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/notebook_extension.py", line 5, in load_ipython_extension
    style=no_style())
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/shells.py", line 94, in import_objects
    from django.db.models.loading import get_models, get_apps
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/__init__.py", line 6, in <module>
    from django.db.models.query import Q
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 17, in <module>
    from django.db.models.deletion import Collector
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 4, in <module>
    from django.db.models import signals, sql
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/__init__.py", line 4, in <module>
    from django.db.models.sql.subqueries import *
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/subqueries.py", line 12, in <module>
    from django.db.models.sql.query import Query
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 22, in <module>
    from django.db.models.sql import aggregates as base_aggregates_module
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/aggregates.py", line 9, in <module>
    ordinal_aggregate_field = IntegerField()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 116, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'founders.settings' (Is it on sys.path? Is there an import error in the settings file?): Could not import settings 'founders.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name models
```

pip freeze is:  (important ones are latest ipython/jupyter & django 1.6.11)

```
aloe==0.0.31
aloe-django==0.0.15
amqp==1.4.7
anyjson==0.3.3
apt-xapian-index==0.44
Babel==2.1.1
backports-abc==0.4
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.21
bitly-api==0.3
blessings==1.6
boto==2.36.0
boto3==1.2.2
botocore==1.3.9
celery==3.1.19
certifi==2015.11.20
chardet==2.0.1
Collectfast==0.2.3
command-not-found==0.2.44
configobj==4.7.2
coverage==4.0
cssselect==0.9.1
decorator==4.0.4
dendrite==1.1.3
diff-match-patch==20121119
dj-database-url==0.3.0
Django==1.6.11
django-appconf==1.0.1
django-autoconfig==0.3.3
django-autoslug==1.7.2
django-braces==1.8.1
django-celery==3.1.16
django-celery-with-redis==3.0
django-compressor==1.3
django-crispy-forms==1.4.0
django-donations==0.2.3
django-environ==0.4.0
django-extensions==1.5.9
django-fsm==2.2.0
django-fsm-admin==1.2.2
django-fsm-log==1.2.1
django-ical==1.3
django-import-export==0.2.6
django-jsonfield==0.9.2
django-keen==0.1.3
django-mixins==0.0.10
django-money==0.7.3
django-nose==1.4.2
django-phonenumber-field==1.0.0
django-registration==1.0
django-robots==1.1
django-shortuuidfield==0.1.2
django-simple-history==1.6.3
django-storages==1.1.8
django-taggit==0.17.5
django-timedeltafield==0.7.10
django-updater==0.4.0
django-waffle==0.11
djangorestframework==2.4.4
docopt==0.4.0
docutils==0.12
dogpile.cache==0.5.7
dogpile.core==0.4.1
duedil==0.6.1
ecdsa==0.13
extras==0.0.3
Fabric==1.10.1
functools32==3.2.3.post2
future==0.15.2
futures==2.2.0
fuzzywuzzy==0.8.0
geopy==1.9.1
gherkin3==3.1.2
GnuPGInterface==0.3.2
gunicorn==19.2.0
hitch==0.5.5
honcho==0.6.6
icalendar==3.9.1
ipykernel==4.2.0
ipython==4.0.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jmespath==0.9.0
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
keen==0.3.0
kombu==3.0.29
language-selector==0.1
lettuce==0.2.21
linecache2==1.0.0
lxml==2.3.2
mailchimp==2.0.9
mailchimp3==1.0.11
Markdown==2.6.5
MarkupSafe==0.23
mistune==0.7.1
mock==1.0.1
nbconvert==4.1.0
nbformat==4.0.1
newrelic==2.58.2.45
nose==1.3.7
notebook==4.0.6
oauthlib==1.0.3
opbeat==3.1.3
Padding==0.4
paramiko==1.16.0
path.py==8.1.2
pbr==1.8.1
pexpect==4.0.1
phonenumbers==7.1.1
pickleshare==0.5
Pillow==3.0.0
pipetools==0.2.7
pluggy==0.3.1
pretend==1.0.8
psycopg2==2.6.1
ptyprocess==0.5
py==1.4.20
py-moneyed==0.6.0
pycrypto==2.6.1
pycurl==7.19.0
pygal==2.0.11
pygeocoder==1.2.5
Pygments==2.0.2
python-apt===0.8.3ubuntu7
python-dateutil==2.4.2
python-debian===0.1.21ubuntu1
python-Levenshtein==0.12.0
python-linkedin==4.1
python-mimeparse==0.1.4
python-subunit==1.1.0
pytz==2015.7
PyYAML==3.11
pyzmq==15.1.0
qtconsole==4.1.1
redis==2.10.5
repoze.lru==0.6
requests==2.8.1
requests-mock==0.7.0
requests-oauth2==0.2.0
requests-oauthlib==0.3.3
retrying==1.3.3
selenium==2.48.0
sh==1.11
shortuuid==0.4.2
simple-history==1.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.9.0
South==1.0.2
splinter==0.7.3
sure==1.2.24
tablib==0.10.0
terminado==0.5
testtools==1.8.0
tornado==4.3
tox==2.1.1
traceback2==1.4.0
traitlets==4.0.0
ufw==0.31.1.post1
unattended-upgrades==0.1
unittest2==1.1.0
virtualenv==13.1.2
Werkzeug==0.10.4
yell==0.3.2
```

Any hints are what might be the problem would be greatly appreciated and apologies if this is an issue with another package, this seemed like the best place to start asking as I am a bit lost :)

The cyclic import appears in django/db/models/__init__.py when trying to import get_apps, get_models etc. models.db.models.signals looks to be the problem..

**Comment by nanorepublica** [comment]
I have now realise that is another library that is causing the problem

**Comment by trbs** [comment]
Happy to hear that you found the issue :)

**Comment by BracketDevs** [comment]
"Another library" is super helpful to those reading this and experiencing similar issues.

Could you please elaborate?

**Comment by nanorepublica** [comment]
Unfortunately I honestly cannot remember which library it was, the point was that is was simply nothing to do with django-extensions. When this happens it could be any other package/library or your own code causing the problem. I would suggest systematically going through your settings.py to work out where your problem is.

**Comment by BracketDevs** [comment]
Thanks for the quick response.

I get this same error whenever I actually open the notebook in Jupyter's browser interface, ie before any notebook code is executed.  
Everything ran fine prior,  issue arose after I was setting up an anaconda virtual environment so potentially package or version conflict on some level or some misconfiguration of ipython as the error text indicates.
