### ISSUE TITLE
Graph Models fails under Django 1.9

### ISSUE THREAD

**Issue by vanflymen** [django-extensions/django-extensions#775]
`python manage.py graph_models -a -o myapp_models.png` fails with:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pycharm\django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "C:\Python27\Lib\runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dan\Documents\GitHub\my_app\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django\core\management\__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django\core\management\__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django\core\management\__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django_extensions\management\commands\graph_models.py", line 8, in <module>
    from django_extensions.management.modelviz import generate_dot
  File "C:\Users\dan\Environments\my_app\lib\site-packages\django_extensions\management\modelviz.py", line 15, in <module>
    from django.db.models import get_models

ImportError: cannot import name get_models
```

Support for `get_models` was dropped in Django 1.9.

**Comment by trbs** [comment]
This should be fixed in the GIT version.
Could you please try with that ?

If would also help testing of our Django 1.9 fixes and getting the next version of Django Extensions out :)
