### ISSUE TITLE
0001_empty django_extensions migration incompatible with python 3.4.0 / django 1.9

### ISSUE THREAD

**Issue by owocki** [django-extensions/django-extensions#776]
`python3 manage.py runserver` with django 1.9 installed generates a 

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff8e20ff620>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 171, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 113, in load_disk
    app_config.label,
TypeError: object() takes no parameters
```

when `migration_name,='0001_empty',app_config.label='django_extensions'`.

System specs:
```
Python 3.4.0
Django 1.9
Ubuntu
```

**Comment by owocki** [comment]
And... nevermind, upgrade to `1.5.9` fixes this issue.

**Comment by adam704a** [comment]
I am seeing the same thing here. upgrade what to 1.5.9?

**Comment by owocki** [comment]
@adam704a `django_extensions`

**Comment by eve1234** [comment]
Thank you

I think it solved my problem too. Though, i had to restart the PC after the upgrade to get it working.
