### ISSUE TITLE
Issue while trying to run graph_models django 1.9

### ISSUE THREAD

**Issue by RylanGotto** [django-extensions/django-extensions#779]
Just recently switch to django 1.9 and have been getting the following traceback with this command?
Is this supported in 1.9? 

python manage.py graph_models -a -o myapp_models.png

Cheers, Rylan

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/commands/graph_models.py", line 8, in <module>
    from django_extensions.management.modelviz import generate_dot
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/modelviz.py", line 15, in <module>
    from django.db.models import get_models
ImportError: cannot import name get_models

**Comment by trbs** [comment]
Could you try with the git version of django-extensions ? this should be solved.

P.S. You can expect a new release on PyPi very soon.

**Comment by RylanGotto** [comment]
Great thank you!
