### ISSUE TITLE
The `create_jobs` command does not work with django 1.9

### ISSUE THREAD

**Issue by xxxss** [django-extensions/django-extensions#795]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 512, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 523, in handle_app_config
    "Subclasses of AppCommand must provide"
NotImplementedError: Subclasses of AppCommand must providea handle_app_config() method.

**Comment by exp0nge** [comment]
In addition to this, `ImportError: No module named south.v2` is thrown out if South is not installed

**Comment by trbs** [comment]
@exp0nge i see no such error, are you sure you are using the github version ?

**Comment by catskul** [comment]
It's because you have an old version of django extensions. 1.5 won't work, you'll need 1.6.+

**Comment by miniyuuzhan** [comment]
I have a similar error 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "env/local/lib/python2.7/site-packages/django/core/management/base.py", line 512, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "env/local/lib/python2.7/site-packages/django/core/management/base.py", line 523, in handle_app_config
    "Subclasses of AppCommand must provide"
NotImplementedError: Subclasses of AppCommand must providea handle_app_config() method.

Result of my pip freeze:

Django==1.9.5
django-extensions==1.6.1

Error raised when trying : __python manage.py create_jobs myapp__

**Comment by trbs** [comment]
Could you please try with the latest version on github ?

**Comment by miniyuuzhan** [comment]
Okay, so i uninstalled django-extensions using pip.
then did this :
pip install -e git+https://github.com/django-extensions/django-extensions.git#egg=django-extensions
then :
python manage.py create_jobs myapp
And it worked just fine.

It has to do with the version installed with pip.

Could you tell when the pip version is updated to the github version ?
Cause it messes with my pip freeze :)
Django==1.9.5
-e git+https://github.com/django-extensions/django-extensions.git@cbdca423de8a89cf4bb368e1153994ed9034af1b#egg=django_extensions-master

**Comment by trbs** [comment]
New release is out on pypi: https://pypi.python.org/pypi/django-extensions/1.6.3

Please test since it's a very big release.
