### ISSUE TITLE
create_command doesn't work on django 1.9

### ISSUE THREAD

**Issue by pbassut** [django-extensions/django-extensions#798]
This is probably similar to #795 but with the create_command instead.
I get this when I try it:
```python
/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/base.py", line 512, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/django/core/management/base.py", line 523, in handle_app_config
    "Subclasses of AppCommand must provide"
NotImplementedError: Subclasses of AppCommand must providea handle_app_config() method.
```

**Comment by trbs** [comment]
This is fixed in the github version.

A new release is waiting on validation of a solution for the JSONField issues though...

**Comment by ad-m** [comment]
```
$ manage.py create_template_tags main --name raven_js
manage.py path: ../../manage.py
Traceback (most recent call last):
  File "../../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 512, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 523, in handle_app_config
    "Subclasses of AppCommand must provide"
NotImplementedError: Subclasses of AppCommand must providea handle_app_config() method.
$ manage.py shell
manage.py path: ../../manage.py
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import django

In [2]: django.VERSION
Out[2]: (1, 9, 5, 'final', 0)

In [3]: import django_extensions

In [4]: django_extensions.VERSION
Out[4]: (1, 6, 7)
```

**Comment by ad-m** [comment]
```
$ pip install https://github.com/django-extensions/django-extensions/archive/master.tar.gz -U
Downloading/unpacking https://github.com/django-extensions/django-extensions/archive/master.tar.gz
  Downloading master.tar.gz (unknown size): 176kB downloaded
  Running setup.py (path:/tmp/pip-YhExea-build/setup.py) egg_info for package from https://github.com/django-extensions/django-extensions/archive/master.tar.gz
    
Requirement already up-to-date: six>=1.2 in /home/adas/.virtualenvs/bliski_publikator/lib/python2.7/site-packages (from django-extensions==1.6.8)
Installing collected packages: django-extensions
  Found existing installation: django-extensions 1.6.7
    Uninstalling django-extensions:
      Successfully uninstalled django-extensions
  Running setup.py install for django-extensions
    
Successfully installed django-extensions
Cleaning up...
(bliski_publikator) ✔ ~/Devel/bliski_publikator/bliski_publikator/main [master|✔] 
$ manage.py create_template_tags main --name raven_js
manage.py path: ../../manage.py
Traceback (most recent call last):
  File "../../manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 512, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "/home/adas/.virtualenvs/bliski_publikator/local/lib/python2.7/site-packages/django/core/management/base.py", line 523, in handle_app_config
    "Subclasses of AppCommand must provide"
NotImplementedError: Subclasses of AppCommand must providea handle_app_config() method.
```
