### ISSUE TITLE
Python 3.4 runprofileserver NameError: free variable 'hotshot' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by mbande** [django-extensions/django-extensions#814]
trying to run ```runprofileserver```, the server starts, but the following error appears upon request:
```
[24/Jan/2016 09:57:15] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/bande/.local/lib/python3.4/site-packages/django_extensions/management/commands/runprofileserver.py", line 238, in handler
    prof = hotshot.Profile(profname)
NameError: free variable 'hotshot' referenced before assignment in enclosing scope
```

**Comment by trbs** [comment]
62bb7710b16d8dfe68eb483cc6bfedb763e5bb45 adds a slightly better error message for when hotspot is not available.
