### ISSUE TITLE
MemoryError on runscript command

### ISSUE THREAD

**Issue by vaibhav-jain** [django-extensions/django-extensions#844]
I have dumped the data using `dumpscript` but when I try to load the data an error is raised

`
(py3) $python manage.py runscript all_data
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django\core\management\base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\utils.py", line 57, in inner
    ret = func(self, *args, **kwargs)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\commands\runscript.py", line 163, in handle
    modules = find_modules_for_script(script)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\commands\runscript.py", line 146, in find_modules_for_script
    mod = my_import(nn)
  File "C:\Users\vaibh\envs\py3\lib\site-packages\django_extensions\management\commands\runscript.py", line 99, in my_import
    importlib.import_module(mod)
  File "C:\Users\vaibh\envs\py3\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
MemoryError`

`all_data.py is in scripts package`. Can you tell me what is wrong??

**Comment by trbs** [comment]
You should check the filesize of ```all_data.py``` if it's really large then most likely you are hitting some memory limit some where.

Since the scripts from ```dumpscript``` are Python files they are not really suitable for really large sets of data. For those using database tools, fixtures or some custom loading scripts is probably better (and a _lot_ faster ;)
