### ISSUE TITLE
find_template doesn't work on Django 1.9

### ISSUE THREAD

**Issue by yprez** [django-extensions/django-extensions#849]
```
$ python manage.py find_template sometemplate
```

Result:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/.../site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/.../site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.../site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/.../site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/.../site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/.../site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "/.../site-packages/django_extensions/management/utils.py", line 57, in inner
    ret = func(self, *args, **kwargs)
  File "/.../site-packages/django_extensions/management/commands/find_template.py", line 33, in handle_label
    path = get_template_path(template_path)
  File "/.../site-packages/django_extensions/management/commands/find_template.py", line 11, in get_template_path
    template = loader.find_template(path)
AttributeError: 'module' object has no attribute 'find_template'
```

https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/find_template.py

It's also not in the docs and there are no tests for it.

Should it be fixed or removed?

**Comment by trbs** [comment]
Seems to work. If there still issues please add a test case to the tests and/or submit a fix.

**Comment by yprez** [comment]
Thanks @trbs, I don't think this matters much anymore, since Django 1.9 is not supported anymore and it seems to work fine on other versions.
