### ISSUE TITLE
"ImportError: No module named moves" in shell_plus ipython with autoreload on

### ISSUE THREAD

**Issue by ramusus** [django-extensions/django-extensions#850]
With 1.6.1 version using `shell_plus` I get this error 

```
[autoreload of manufacture.tasks failed: Traceback (most recent call last):
  File "/Users/ramusus/workspace/manufacture/env/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
ImportError: No module named moves
]
```

after each source file modification with enabled auto reloading feature in `ipython`. My ipython settings

```
c.TerminalInteractiveShell.deep_reload = True
c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
```

Tested in Django 1.7.5 and Django 1.9. The problem the same. 

Full print message:

```
Reloading manufacture.sys
Reloading manufacture.logging
Reloading logging
Reloading logging.sys
Reloading logging.os
Reloading os
Reloading errno
Reloading posix
Reloading posixpath
Reloading stat
Reloading genericpath
Reloading warnings
Reloading linecache
Reloading types
Reloading _warnings
Reloading UserDict
Reloading _abcoll
Reloading abc
Reloading _weakrefset
Reloading _weakref
Reloading copy_reg
Reloading logging.time
Reloading time
Reloading logging.cStringIO
Reloading cStringIO
Reloading logging.traceback
Reloading traceback
Reloading logging.warnings
Reloading logging.weakref
Reloading weakref
Reloading exceptions
Reloading logging.collections
Reloading collections
Reloading _collections
Reloading operator
Reloading keyword
Reloading heapq
Reloading itertools
Reloading _heapq
Reloading thread
Reloading logging.codecs
Reloading codecs
Reloading _codecs
Reloading logging.thread
Reloading logging.threading
Reloading threading
Reloading re
Reloading sre_compile
Reloading _sre
Reloading sre_parse
Reloading sre_constants
Reloading _locale
Reloading logging.atexit
Reloading atexit
Reloading manufacture.datetime
Reloading datetime
Reloading manufacture.random
Reloading random
Reloading __future__
Reloading math
Reloading binascii
Reloading hashlib
Reloading _hashlib
Reloading struct
Reloading _struct
Reloading _random
Reloading manufacture.alert
Reloading alert
Reloading alert.models
Reloading alert.datetime
Reloading alert.django
Reloading django
Reloading django.conf
Reloading django.conf.importlib
Reloading importlib
Reloading importlib.sys
Reloading django.conf.os
Reloading django.conf.time
Reloading django.conf.django
Reloading django.core
Reloading django.core.exceptions
Reloading django.core.functools
Reloading functools
Reloading _functools
Reloading django.core.operator
Reloading django.core.django
Reloading django.utils
Reloading django.utils.encoding
Reloading django.utils.__future__
Reloading django.utils.codecs
Reloading django.utils.datetime
Reloading django.utils.decimal
Reloading decimal
Reloading numbers
Reloading locale
Reloading encodings
Reloading encodings.codecs
Reloading encodings.encodings
Reloading encodings.__builtin__
Reloading encodings.aliases
Reloading django.utils.locale
Reloading django.utils.django
Reloading django.utils.functional
Reloading django.utils.copy
Reloading copy
Reloading org
Reloading django.utils.operator
Reloading django.utils.functools
Reloading django.utils.sys
Reloading django.utils.warnings
Reloading django.utils.deprecation
Reloading django.utils.inspect
Reloading inspect
Reloading string
Reloading strop
Reloading dis
Reloading opcode
Reloading imp
Reloading tokenize
Reloading token
Reloading django.utils.six
Reloading StringIO
Reloading django.utils.six.moves
[autoreload of manufacture.tasks failed: Traceback (most recent call last):
  File "/Users/ramusus/workspace/manufacture/env/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
ImportError: No module named moves
]
```

**Comment by trbs** [comment]
If this is still an issue please open a new ticket
