### ISSUE TITLE
LookupError: No installed app with label '<module 'django.contrib.admin.models' from '[...]'>'.

### ISSUE THREAD

**Issue by alorence** [django-extensions/django-extensions#885]
Hello,

When I run one of these commands, I get the correct output:

    python manage.py dumpscript auth
    python manage.py dumpscript admin

But if I run the same without app name, I get an error
```
python manage.py dumpscript
Traceback (most recent call last):
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\apps\registry.py", line 148, in get_app_config
    return self.app_configs[app_label]
KeyError: <module 'django.contrib.admin.models' from 'F:\\Flux\\CaffeineServer\\venv\\lib\\site-packages\\django\\contrib\\admin\\models.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django_extensions\management\utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django_extensions\management\commands\dumpscript.py", line 102, in handle
    models = get_models(app_labels)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django_extensions\management\commands\dumpscript.py", line 136, in get_models
    models += [m for m in get_models_compat(app)
  File "D:\Dev\path\to\project\venv\lib\site-packages\django_extensions\compat.py", line 153, in get_models_compat
    return apps.get_app_config(app_label).get_models()
  File "D:\Dev\path\to\project\venv\lib\site-packages\django\apps\registry.py", line 155, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label '<module 'django.contrib.admin.models' from 'D:\\Dev\\path\\to\\project\\venv\\lib\\site-packages\\django\\contrib\\admin\\models.py'>'.
(venv)
```

Setting some breakpoints try to find a way to fix, I saw the error comes from [that block](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/dumpscript.py#L135) in dumpscript.py:
```
    # If no app labels are given, return all
    if not app_labels:
        for app in get_apps():
            models += [m for m in get_models_compat(app)
                       if m not in EXCLUDED_MODELS]
        return models
```

`get_apps()` returns a list of applications when `get_models_compat(app)` seems to require an app_label instead of an app as argument. I don't know how to fix this issue, so I'm sorry, I will not be able to create a PR.

Regards

Note: Django 1.9.5, django-extensions1.6.3

**Comment by trbs** [comment]
3a0ca9e40a11729d30cc3f2d916c446321805f97 should hopefully fix this.

**Comment by alorence** [comment]
Yeah that sounds good. I can't test right now, but the patch make sense. I will be able to test as soon as a next release will be published on Pypi.

Thanks !

**Comment by trbs** [comment]
1.6.4 is up on PyPi :)

(Please reopen or create a new ticket if this isn't solved)

**Comment by trbs** [comment]
Actually 1.6.5 is the latest version since PyPi borked while uploading 1.6.4...
PyPi seems broken at the moment for uploading wheel packages :(
