### ISSUE TITLE
How to run reset_db on Heroku? Fails with: "User does not have CONNECT privilege."

### ISSUE THREAD

**Issue by cirosantilli** [django-extensions/django-extensions#909]
I can do database operations like `manage.py migrate` normally, but `reset_db` fails with:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.5/site-packages/django_extensions/management/commands/reset_db.py", line 145, in handle
    connection = Database.connect(**conn_params)
  File "/app/.heroku/python/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  permission denied for database "template1"
DETAIL:  User does not have CONNECT privilege.
```

I am using `dj_database_url.config` as mentioned at: https://github.com/heroku/python-getting-started/blob/33fafbd40ff5532def4ce7b3d0ebc1c7e34a0be7/gettingstarted/settings.py#L115

My full project: https://github.com/cirosantilli/free-books-django-raw/tree/1fd154df716e06e02a5a3afa299a89fe5513a112

Tested on Django 1.9.6, django-extensions 1.6.7.

**Comment by trbs** [comment]
Since Heroku is a managed platform you probable do not have access to the "template1" database. However the command needs to connect to something (other then the database you want to reset).

I would happily accept a PR that will make connecting to the "template1" database configurable. My guess is that that still won't help you. Since you are probably not allowed to do the DROP DATABASE and CREATE DATABASE statements as well.

If you want please verify this and make a PR for the documentation so that other people can read about this in the documentation.
