### ISSUE TITLE
Possible issue with shell plus and django 1.10

### ISSUE THREAD

**Issue by SalahAdDin** [django-extensions/django-extensions#911]
Hi guys, i'm testing django 1.10 with my new project and i have the next problem:
```bash
docker exec -it knowledgebase_web_1 python manage.py shell_plus
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/django_extensions/management/commands/shell_plus.py", line 9, in <module>
    from django.core.management.base import NoArgsCommand, CommandError
ImportError: cannot import name 'NoArgsCommand'
```

I have the next django packages:
```
Django==1.10a1
django-appconf==1.0.2
django-axes==1.7.0
django-compressor==2.0
django-extensions==1.6.1
```

Thanks.

**Comment by SalahAdDin** [comment]
It was solved in the last version.
