### ISSUE TITLE
runserver_plus inside Docker exits after Django error

### ISSUE THREAD

**Issue by jonatasbaldin** [django-extensions/django-extensions#960]
I'm running a Docker container (docker-compose) with runserver_plus. When I type some erroneous Python code, the Django server reloads and, presents me the error and then exits with status 1.

It is not viable to use this way, because I have to restart the container every time I make a mistake :(

Traceback:
```
web_1  |  * Restarting with stat
web_1  | Traceback (most recent call last):
web_1  |   File "manage.py", line 10, in <module>
web_1  |     execute_from_command_line(sys.argv)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
web_1  |     utility.execute()
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
web_1  |     self.execute(*args, **cmd_options)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
web_1  |     output = self.handle(*args, **options)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django_extensions/management/utils.py", line 58, in inner
web_1  |     ret = func(self, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django_extensions/management/commands/runserver_plus.py", line 215, in handle
web_1  |     self.inner_run(options)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django_extensions/management/commands/runserver_plus.py", line 256, in inner_run
web_1  |     self.check(display_num_errors=self.show_startup_messages)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
web_1  |     include_deployment_checks=include_deployment_checks,
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
web_1  |     new_errors = check(app_configs=app_configs)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/checks/urls.py", line 13, in check_url_config
web_1  |     return check_resolver(resolver)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/checks/urls.py", line 23, in check_resolver
web_1  |     for pattern in resolver.url_patterns:
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
web_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module                                                                                                                                                   [165/1570]
web_1  |     return import_module(self.urlconf_name)
web_1  |   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1129, in _exec
web_1  |   File "<frozen importlib._bootstrap>", line 1471, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
web_1  |   File "<my-code>", line 27, in <module>
web_1  |     <my-code>
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 52, in include
web_1  |     urlconf_module = import_module(urlconf_module)
web_1  |   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1129, in _exec
web_1  |   File "<frozen importlib._bootstrap>", line 1471, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
web_1  |   File "/code/core/urls.py", line 4, in <module>
web_1  |     url(r'^api/v1/', include('core.api.v1.urls')),
web_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 52, in include
web_1  |     urlconf_module = import_module(urlconf_module)
web_1  |   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 1129, in _exec
web_1  |   File "<frozen importlib._bootstrap>", line 1471, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
web_1  |   File "<my-code>", line 1, in <module>
web_1  |     <my-code>
web_1  |   File "<my-code>", line 58, in <module>
web_1  |     <my-code>:
web_1  |   File "<my-code>", line 59, in <my-code>
web_1  |     <my-code>
web_1  | NameError: name '<my-code>' is not defined
web_1 exited with code 1
```

Docker version:
````
Docker version 1.12.0, build 8eab29e
````

OS:
```
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
```

docker-composer version:
````
docker-compose version 1.8.0, build f3628c7
```

If you need more information, let me know!

**Comment by trbs** [comment]
The reloader that exits on code errors in your example is from the Werkzeug project.
So you could try and submit a ticket there to see if they want to create some option to mimic Django's autoreloader behavior.

In the mean time I suppose you can always do:

```bash
while True; do
    ./manage.py runserver_plus
    sleep 5s
done
```
