### ISSUE TITLE
export_emails not working in Python 3

### ISSUE THREAD

**Issue by catalyst-joe-guo** [django-extensions/django-extensions#993]
```
(discover) joeg@joeg-pc:~/lef/discover(master○) » python manage.py export_emails -f emails
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django_extensions/management/commands/export_emails.py", line 67, in handle
    getattr(self, options['format'])(qs, outfile)
  File "/home/joeg/env/discover/local/lib/python3.5/site-packages/django_extensions/management/commands/export_emails.py", line 81, in emails
    out.write(six.u(",\n").join(ent['email'] for ent in qs).encode(self.encoding))
TypeError: write() argument must be str, not bytes
```

**Comment by nicolasmendoza** [comment]
@trbs can I pick this task?

**Comment by trbs** [comment]
Yes please, always happy to merge a fix ! :)

Regards,
trbs

2017-06-19 15:41 GMT+02:00 Nicolás <notifications@github.com>:

**Comment by nicolasmendoza** [comment]
Work in progress.
